ALTER TABLE users DROP COLUMN IF EXISTS totp_recovery_codes;
ALTER TABLE users DROP COLUMN IF EXISTS totp_enabled;
ALTER TABLE users DROP COLUMN IF EXISTS totp_nonce;
ALTER TABLE users DROP COLUMN IF EXISTS totp_secret;
