// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: workspace/workspace.proto

package workspace

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	common "inkwell/server/pkg/grpc/common"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Category struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Slug          string                 `protobuf:"bytes,2,opt,name=slug,proto3" json:"slug,omitempty"` // novel, screenplay, comic_script, poetry, interactive_fiction, tabletop_rpg, memoir, lyrics
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Icon          string                 `protobuf:"bytes,5,opt,name=icon,proto3" json:"icon,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Category) Reset() {
	*x = Category{}
	mi := &file_workspace_workspace_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Category) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Category) ProtoMessage() {}

func (x *Category) ProtoReflect() protoreflect.Message {
	mi := &file_workspace_workspace_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Category.ProtoReflect.Descriptor instead.
func (*Category) Descriptor() ([]byte, []int) {
	return file_workspace_workspace_proto_rawDescGZIP(), []int{0}
}

func (x *Category) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Category) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *Category) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Category) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Category) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

type Workspace struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Slug          string                 `protobuf:"bytes,3,opt,name=slug,proto3" json:"slug,omitempty"`
	Type          string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"` // personal | org
	OwnerId       string                 `protobuf:"bytes,5,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	AvatarUrl     string                 `protobuf:"bytes,6,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	Description   string                 `protobuf:"bytes,7,opt,name=description,proto3" json:"description,omitempty"`
	Categories    []*Category            `protobuf:"bytes,8,rep,name=categories,proto3" json:"categories,omitempty"`
	CreatedAt     *common.Timestamp      `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *common.Timestamp      `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Workspace) Reset() {
	*x = Workspace{}
	mi := &file_workspace_workspace_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Workspace) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Workspace) ProtoMessage() {}

func (x *Workspace) ProtoReflect() protoreflect.Message {
	mi := &file_workspace_workspace_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Workspace.ProtoReflect.Descriptor instead.
func (*Workspace) Descriptor() ([]byte, []int) {
	return file_workspace_workspace_proto_rawDescGZIP(), []int{1}
}

func (x *Workspace) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Workspace) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Workspace) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *Workspace) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Workspace) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *Workspace) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

func (x *Workspace) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Workspace) GetCategories() []*Category {
	if x != nil {
		return x.Categories
	}
	return nil
}

func (x *Workspace) GetCreatedAt() *common.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Workspace) GetUpdatedAt() *common.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type WorkspaceMember struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	WorkspaceId   string                 `protobuf:"bytes,2,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Role          string                 `protobuf:"bytes,4,opt,name=role,proto3" json:"role,omitempty"` // owner | admin | editor | viewer
	InvitedBy     string                 `protobuf:"bytes,5,opt,name=invited_by,json=invitedBy,proto3" json:"invited_by,omitempty"`
	JoinedAt      *common.Timestamp      `protobuf:"bytes,6,opt,name=joined_at,json=joinedAt,proto3" json:"joined_at,omitempty"`
	CreatedAt     *common.Timestamp      `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkspaceMember) Reset() {
	*x = WorkspaceMember{}
	mi := &file_workspace_workspace_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkspaceMember) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkspaceMember) ProtoMessage() {}

func (x *WorkspaceMember) ProtoReflect() protoreflect.Message {
	mi := &file_workspace_workspace_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkspaceMember.ProtoReflect.Descriptor instead.
func (*WorkspaceMember) Descriptor() ([]byte, []int) {
	return file_workspace_workspace_proto_rawDescGZIP(), []int{2}
}

func (x *WorkspaceMember) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *WorkspaceMember) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *WorkspaceMember) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *WorkspaceMember) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *WorkspaceMember) GetInvitedBy() string {
	if x != nil {
		return x.InvitedBy
	}
	return ""
}

func (x *WorkspaceMember) GetJoinedAt() *common.Timestamp {
	if x != nil {
		return x.JoinedAt
	}
	return nil
}

func (x *WorkspaceMember) GetCreatedAt() *common.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type ListCategoriesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCategoriesRequest) Reset() {
	*x = ListCategoriesRequest{}
	mi := &file_workspace_workspace_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCategoriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCategoriesRequest) ProtoMessage() {}

func (x *ListCategoriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workspace_workspace_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCategoriesRequest.ProtoReflect.Descriptor instead.
func (*ListCategoriesRequest) Descriptor() ([]byte, []int) {
	return file_workspace_workspace_proto_rawDescGZIP(), []int{3}
}

type ListCategoriesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Categories    []*Category            `protobuf:"bytes,1,rep,name=categories,proto3" json:"categories,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCategoriesResponse) Reset() {
	*x = ListCategoriesResponse{}
	mi := &file_workspace_workspace_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCategoriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCategoriesResponse) ProtoMessage() {}

func (x *ListCategoriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_workspace_workspace_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCategoriesResponse.ProtoReflect.Descriptor instead.
func (*ListCategoriesResponse) Descriptor() ([]byte, []int) {
	return file_workspace_workspace_proto_rawDescGZIP(), []int{4}
}

func (x *ListCategoriesResponse) GetCategories() []*Category {
	if x != nil {
		return x.Categories
	}
	return nil
}

type CreatePersonalWorkspacesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // called on registration, creates one workspace per category slug provided
	CategorySlugs []string               `protobuf:"bytes,2,rep,name=category_slugs,json=categorySlugs,proto3" json:"category_slugs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePersonalWorkspacesRequest) Reset() {
	*x = CreatePersonalWorkspacesRequest{}
	mi := &file_workspace_workspace_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePersonalWorkspacesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePersonalWorkspacesRequest) ProtoMessage() {}

func (x *CreatePersonalWorkspacesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workspace_workspace_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePersonalWorkspacesRequest.ProtoReflect.Descriptor instead.
func (*CreatePersonalWorkspacesRequest) Descriptor() ([]byte, []int) {
	return file_workspace_workspace_proto_rawDescGZIP(), []int{5}
}

func (x *CreatePersonalWorkspacesRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreatePersonalWorkspacesRequest) GetCategorySlugs() []string {
	if x != nil {
		return x.CategorySlugs
	}
	return nil
}

type CreatePersonalWorkspacesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Workspaces    []*Workspace           `protobuf:"bytes,1,rep,name=workspaces,proto3" json:"workspaces,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePersonalWorkspacesResponse) Reset() {
	*x = CreatePersonalWorkspacesResponse{}
	mi := &file_workspace_workspace_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePersonalWorkspacesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePersonalWorkspacesResponse) ProtoMessage() {}

func (x *CreatePersonalWorkspacesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_workspace_workspace_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePersonalWorkspacesResponse.ProtoReflect.Descriptor instead.
func (*CreatePersonalWorkspacesResponse) Descriptor() ([]byte, []int) {
	return file_workspace_workspace_proto_rawDescGZIP(), []int{6}
}

func (x *CreatePersonalWorkspacesResponse) GetWorkspaces() []*Workspace {
	if x != nil {
		return x.Workspaces
	}
	return nil
}

type CreateOrgWorkspaceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OwnerId       string                 `protobuf:"bytes,1,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	CategorySlugs []string               `protobuf:"bytes,4,rep,name=category_slugs,json=categorySlugs,proto3" json:"category_slugs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrgWorkspaceRequest) Reset() {
	*x = CreateOrgWorkspaceRequest{}
	mi := &file_workspace_workspace_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrgWorkspaceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrgWorkspaceRequest) ProtoMessage() {}

func (x *CreateOrgWorkspaceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workspace_workspace_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrgWorkspaceRequest.ProtoReflect.Descriptor instead.
func (*CreateOrgWorkspaceRequest) Descriptor() ([]byte, []int) {
	return file_workspace_workspace_proto_rawDescGZIP(), []int{7}
}

func (x *CreateOrgWorkspaceRequest) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *CreateOrgWorkspaceRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateOrgWorkspaceRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateOrgWorkspaceRequest) GetCategorySlugs() []string {
	if x != nil {
		return x.CategorySlugs
	}
	return nil
}

type CreateOrgWorkspaceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Workspace     *Workspace             `protobuf:"bytes,1,opt,name=workspace,proto3" json:"workspace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrgWorkspaceResponse) Reset() {
	*x = CreateOrgWorkspaceResponse{}
	mi := &file_workspace_workspace_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrgWorkspaceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrgWorkspaceResponse) ProtoMessage() {}

func (x *CreateOrgWorkspaceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_workspace_workspace_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrgWorkspaceResponse.ProtoReflect.Descriptor instead.
func (*CreateOrgWorkspaceResponse) Descriptor() ([]byte, []int) {
	return file_workspace_workspace_proto_rawDescGZIP(), []int{8}
}

func (x *CreateOrgWorkspaceResponse) GetWorkspace() *Workspace {
	if x != nil {
		return x.Workspace
	}
	return nil
}

type GetWorkspaceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkspaceId   string                 `protobuf:"bytes,1,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWorkspaceRequest) Reset() {
	*x = GetWorkspaceRequest{}
	mi := &file_workspace_workspace_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWorkspaceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWorkspaceRequest) ProtoMessage() {}

func (x *GetWorkspaceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workspace_workspace_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWorkspaceRequest.ProtoReflect.Descriptor instead.
func (*GetWorkspaceRequest) Descriptor() ([]byte, []int) {
	return file_workspace_workspace_proto_rawDescGZIP(), []int{9}
}

func (x *GetWorkspaceRequest) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

type GetWorkspaceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Workspace     *Workspace             `protobuf:"bytes,1,opt,name=workspace,proto3" json:"workspace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWorkspaceResponse) Reset() {
	*x = GetWorkspaceResponse{}
	mi := &file_workspace_workspace_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWorkspaceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWorkspaceResponse) ProtoMessage() {}

func (x *GetWorkspaceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_workspace_workspace_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWorkspaceResponse.ProtoReflect.Descriptor instead.
func (*GetWorkspaceResponse) Descriptor() ([]byte, []int) {
	return file_workspace_workspace_proto_rawDescGZIP(), []int{10}
}

func (x *GetWorkspaceResponse) GetWorkspace() *Workspace {
	if x != nil {
		return x.Workspace
	}
	return nil
}

type ListUserWorkspacesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUserWorkspacesRequest) Reset() {
	*x = ListUserWorkspacesRequest{}
	mi := &file_workspace_workspace_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUserWorkspacesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserWorkspacesRequest) ProtoMessage() {}

func (x *ListUserWorkspacesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workspace_workspace_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserWorkspacesRequest.ProtoReflect.Descriptor instead.
func (*ListUserWorkspacesRequest) Descriptor() ([]byte, []int) {
	return file_workspace_workspace_proto_rawDescGZIP(), []int{11}
}

func (x *ListUserWorkspacesRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type ListUserWorkspacesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Personal      []*Workspace           `protobuf:"bytes,1,rep,name=personal,proto3" json:"personal,omitempty"`
	Org           []*Workspace           `protobuf:"bytes,2,rep,name=org,proto3" json:"org,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUserWorkspacesResponse) Reset() {
	*x = ListUserWorkspacesResponse{}
	mi := &file_workspace_workspace_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUserWorkspacesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserWorkspacesResponse) ProtoMessage() {}

func (x *ListUserWorkspacesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_workspace_workspace_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserWorkspacesResponse.ProtoReflect.Descriptor instead.
func (*ListUserWorkspacesResponse) Descriptor() ([]byte, []int) {
	return file_workspace_workspace_proto_rawDescGZIP(), []int{12}
}

func (x *ListUserWorkspacesResponse) GetPersonal() []*Workspace {
	if x != nil {
		return x.Personal
	}
	return nil
}

func (x *ListUserWorkspacesResponse) GetOrg() []*Workspace {
	if x != nil {
		return x.Org
	}
	return nil
}

type UpdateWorkspaceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkspaceId   string                 `protobuf:"bytes,1,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	AvatarUrl     string                 `protobuf:"bytes,4,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateWorkspaceRequest) Reset() {
	*x = UpdateWorkspaceRequest{}
	mi := &file_workspace_workspace_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateWorkspaceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateWorkspaceRequest) ProtoMessage() {}

func (x *UpdateWorkspaceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workspace_workspace_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateWorkspaceRequest.ProtoReflect.Descriptor instead.
func (*UpdateWorkspaceRequest) Descriptor() ([]byte, []int) {
	return file_workspace_workspace_proto_rawDescGZIP(), []int{13}
}

func (x *UpdateWorkspaceRequest) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *UpdateWorkspaceRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateWorkspaceRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateWorkspaceRequest) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

type UpdateWorkspaceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Workspace     *Workspace             `protobuf:"bytes,1,opt,name=workspace,proto3" json:"workspace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateWorkspaceResponse) Reset() {
	*x = UpdateWorkspaceResponse{}
	mi := &file_workspace_workspace_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateWorkspaceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateWorkspaceResponse) ProtoMessage() {}

func (x *UpdateWorkspaceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_workspace_workspace_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateWorkspaceResponse.ProtoReflect.Descriptor instead.
func (*UpdateWorkspaceResponse) Descriptor() ([]byte, []int) {
	return file_workspace_workspace_proto_rawDescGZIP(), []int{14}
}

func (x *UpdateWorkspaceResponse) GetWorkspace() *Workspace {
	if x != nil {
		return x.Workspace
	}
	return nil
}

type DeleteWorkspaceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkspaceId   string                 `protobuf:"bytes,1,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // must be owner
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteWorkspaceRequest) Reset() {
	*x = DeleteWorkspaceRequest{}
	mi := &file_workspace_workspace_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteWorkspaceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteWorkspaceRequest) ProtoMessage() {}

func (x *DeleteWorkspaceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workspace_workspace_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteWorkspaceRequest.ProtoReflect.Descriptor instead.
func (*DeleteWorkspaceRequest) Descriptor() ([]byte, []int) {
	return file_workspace_workspace_proto_rawDescGZIP(), []int{15}
}

func (x *DeleteWorkspaceRequest) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *DeleteWorkspaceRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type DeleteWorkspaceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteWorkspaceResponse) Reset() {
	*x = DeleteWorkspaceResponse{}
	mi := &file_workspace_workspace_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteWorkspaceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteWorkspaceResponse) ProtoMessage() {}

func (x *DeleteWorkspaceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_workspace_workspace_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteWorkspaceResponse.ProtoReflect.Descriptor instead.
func (*DeleteWorkspaceResponse) Descriptor() ([]byte, []int) {
	return file_workspace_workspace_proto_rawDescGZIP(), []int{16}
}

func (x *DeleteWorkspaceResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type EnableCategoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkspaceId   string                 `protobuf:"bytes,1,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	CategorySlug  string                 `protobuf:"bytes,2,opt,name=category_slug,json=categorySlug,proto3" json:"category_slug,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnableCategoryRequest) Reset() {
	*x = EnableCategoryRequest{}
	mi := &file_workspace_workspace_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnableCategoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnableCategoryRequest) ProtoMessage() {}

func (x *EnableCategoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workspace_workspace_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnableCategoryRequest.ProtoReflect.Descriptor instead.
func (*EnableCategoryRequest) Descriptor() ([]byte, []int) {
	return file_workspace_workspace_proto_rawDescGZIP(), []int{17}
}

func (x *EnableCategoryRequest) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *EnableCategoryRequest) GetCategorySlug() string {
	if x != nil {
		return x.CategorySlug
	}
	return ""
}

type EnableCategoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Workspace     *Workspace             `protobuf:"bytes,1,opt,name=workspace,proto3" json:"workspace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnableCategoryResponse) Reset() {
	*x = EnableCategoryResponse{}
	mi := &file_workspace_workspace_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnableCategoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnableCategoryResponse) ProtoMessage() {}

func (x *EnableCategoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_workspace_workspace_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnableCategoryResponse.ProtoReflect.Descriptor instead.
func (*EnableCategoryResponse) Descriptor() ([]byte, []int) {
	return file_workspace_workspace_proto_rawDescGZIP(), []int{18}
}

func (x *EnableCategoryResponse) GetWorkspace() *Workspace {
	if x != nil {
		return x.Workspace
	}
	return nil
}

type DisableCategoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkspaceId   string                 `protobuf:"bytes,1,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	CategorySlug  string                 `protobuf:"bytes,2,opt,name=category_slug,json=categorySlug,proto3" json:"category_slug,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisableCategoryRequest) Reset() {
	*x = DisableCategoryRequest{}
	mi := &file_workspace_workspace_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisableCategoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisableCategoryRequest) ProtoMessage() {}

func (x *DisableCategoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workspace_workspace_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisableCategoryRequest.ProtoReflect.Descriptor instead.
func (*DisableCategoryRequest) Descriptor() ([]byte, []int) {
	return file_workspace_workspace_proto_rawDescGZIP(), []int{19}
}

func (x *DisableCategoryRequest) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *DisableCategoryRequest) GetCategorySlug() string {
	if x != nil {
		return x.CategorySlug
	}
	return ""
}

type DisableCategoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Workspace     *Workspace             `protobuf:"bytes,1,opt,name=workspace,proto3" json:"workspace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisableCategoryResponse) Reset() {
	*x = DisableCategoryResponse{}
	mi := &file_workspace_workspace_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisableCategoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisableCategoryResponse) ProtoMessage() {}

func (x *DisableCategoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_workspace_workspace_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisableCategoryResponse.ProtoReflect.Descriptor instead.
func (*DisableCategoryResponse) Descriptor() ([]byte, []int) {
	return file_workspace_workspace_proto_rawDescGZIP(), []int{20}
}

func (x *DisableCategoryResponse) GetWorkspace() *Workspace {
	if x != nil {
		return x.Workspace
	}
	return nil
}

type AddMemberRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkspaceId   string                 `protobuf:"bytes,1,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Role          string                 `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`
	InvitedBy     string                 `protobuf:"bytes,4,opt,name=invited_by,json=invitedBy,proto3" json:"invited_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddMemberRequest) Reset() {
	*x = AddMemberRequest{}
	mi := &file_workspace_workspace_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddMemberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddMemberRequest) ProtoMessage() {}

func (x *AddMemberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workspace_workspace_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddMemberRequest.ProtoReflect.Descriptor instead.
func (*AddMemberRequest) Descriptor() ([]byte, []int) {
	return file_workspace_workspace_proto_rawDescGZIP(), []int{21}
}

func (x *AddMemberRequest) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *AddMemberRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AddMemberRequest) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *AddMemberRequest) GetInvitedBy() string {
	if x != nil {
		return x.InvitedBy
	}
	return ""
}

type AddMemberResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Member        *WorkspaceMember       `protobuf:"bytes,1,opt,name=member,proto3" json:"member,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddMemberResponse) Reset() {
	*x = AddMemberResponse{}
	mi := &file_workspace_workspace_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddMemberResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddMemberResponse) ProtoMessage() {}

func (x *AddMemberResponse) ProtoReflect() protoreflect.Message {
	mi := &file_workspace_workspace_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddMemberResponse.ProtoReflect.Descriptor instead.
func (*AddMemberResponse) Descriptor() ([]byte, []int) {
	return file_workspace_workspace_proto_rawDescGZIP(), []int{22}
}

func (x *AddMemberResponse) GetMember() *WorkspaceMember {
	if x != nil {
		return x.Member
	}
	return nil
}

type RemoveMemberRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkspaceId   string                 `protobuf:"bytes,1,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveMemberRequest) Reset() {
	*x = RemoveMemberRequest{}
	mi := &file_workspace_workspace_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveMemberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveMemberRequest) ProtoMessage() {}

func (x *RemoveMemberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workspace_workspace_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveMemberRequest.ProtoReflect.Descriptor instead.
func (*RemoveMemberRequest) Descriptor() ([]byte, []int) {
	return file_workspace_workspace_proto_rawDescGZIP(), []int{23}
}

func (x *RemoveMemberRequest) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *RemoveMemberRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type RemoveMemberResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveMemberResponse) Reset() {
	*x = RemoveMemberResponse{}
	mi := &file_workspace_workspace_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveMemberResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveMemberResponse) ProtoMessage() {}

func (x *RemoveMemberResponse) ProtoReflect() protoreflect.Message {
	mi := &file_workspace_workspace_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveMemberResponse.ProtoReflect.Descriptor instead.
func (*RemoveMemberResponse) Descriptor() ([]byte, []int) {
	return file_workspace_workspace_proto_rawDescGZIP(), []int{24}
}

func (x *RemoveMemberResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type UpdateMemberRoleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkspaceId   string                 `protobuf:"bytes,1,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Role          string                 `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMemberRoleRequest) Reset() {
	*x = UpdateMemberRoleRequest{}
	mi := &file_workspace_workspace_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMemberRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMemberRoleRequest) ProtoMessage() {}

func (x *UpdateMemberRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workspace_workspace_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMemberRoleRequest.ProtoReflect.Descriptor instead.
func (*UpdateMemberRoleRequest) Descriptor() ([]byte, []int) {
	return file_workspace_workspace_proto_rawDescGZIP(), []int{25}
}

func (x *UpdateMemberRoleRequest) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *UpdateMemberRoleRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdateMemberRoleRequest) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

type UpdateMemberRoleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Member        *WorkspaceMember       `protobuf:"bytes,1,opt,name=member,proto3" json:"member,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMemberRoleResponse) Reset() {
	*x = UpdateMemberRoleResponse{}
	mi := &file_workspace_workspace_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMemberRoleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMemberRoleResponse) ProtoMessage() {}

func (x *UpdateMemberRoleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_workspace_workspace_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMemberRoleResponse.ProtoReflect.Descriptor instead.
func (*UpdateMemberRoleResponse) Descriptor() ([]byte, []int) {
	return file_workspace_workspace_proto_rawDescGZIP(), []int{26}
}

func (x *UpdateMemberRoleResponse) GetMember() *WorkspaceMember {
	if x != nil {
		return x.Member
	}
	return nil
}

type ListMembersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkspaceId   string                 `protobuf:"bytes,1,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMembersRequest) Reset() {
	*x = ListMembersRequest{}
	mi := &file_workspace_workspace_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMembersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMembersRequest) ProtoMessage() {}

func (x *ListMembersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workspace_workspace_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMembersRequest.ProtoReflect.Descriptor instead.
func (*ListMembersRequest) Descriptor() ([]byte, []int) {
	return file_workspace_workspace_proto_rawDescGZIP(), []int{27}
}

func (x *ListMembersRequest) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

type ListMembersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Members       []*WorkspaceMember     `protobuf:"bytes,1,rep,name=members,proto3" json:"members,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMembersResponse) Reset() {
	*x = ListMembersResponse{}
	mi := &file_workspace_workspace_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMembersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMembersResponse) ProtoMessage() {}

func (x *ListMembersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_workspace_workspace_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMembersResponse.ProtoReflect.Descriptor instead.
func (*ListMembersResponse) Descriptor() ([]byte, []int) {
	return file_workspace_workspace_proto_rawDescGZIP(), []int{28}
}

func (x *ListMembersResponse) GetMembers() []*WorkspaceMember {
	if x != nil {
		return x.Members
	}
	return nil
}

type InviteMemberRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkspaceId   string                 `protobuf:"bytes,1,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Role          string                 `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`
	InvitedBy     string                 `protobuf:"bytes,4,opt,name=invited_by,json=invitedBy,proto3" json:"invited_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InviteMemberRequest) Reset() {
	*x = InviteMemberRequest{}
	mi := &file_workspace_workspace_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InviteMemberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InviteMemberRequest) ProtoMessage() {}

func (x *InviteMemberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workspace_workspace_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InviteMemberRequest.ProtoReflect.Descriptor instead.
func (*InviteMemberRequest) Descriptor() ([]byte, []int) {
	return file_workspace_workspace_proto_rawDescGZIP(), []int{29}
}

func (x *InviteMemberRequest) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *InviteMemberRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *InviteMemberRequest) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *InviteMemberRequest) GetInvitedBy() string {
	if x != nil {
		return x.InvitedBy
	}
	return ""
}

type InviteMemberResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InviteToken   string                 `protobuf:"bytes,1,opt,name=invite_token,json=inviteToken,proto3" json:"invite_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InviteMemberResponse) Reset() {
	*x = InviteMemberResponse{}
	mi := &file_workspace_workspace_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InviteMemberResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InviteMemberResponse) ProtoMessage() {}

func (x *InviteMemberResponse) ProtoReflect() protoreflect.Message {
	mi := &file_workspace_workspace_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InviteMemberResponse.ProtoReflect.Descriptor instead.
func (*InviteMemberResponse) Descriptor() ([]byte, []int) {
	return file_workspace_workspace_proto_rawDescGZIP(), []int{30}
}

func (x *InviteMemberResponse) GetInviteToken() string {
	if x != nil {
		return x.InviteToken
	}
	return ""
}

type AcceptInviteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcceptInviteRequest) Reset() {
	*x = AcceptInviteRequest{}
	mi := &file_workspace_workspace_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptInviteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptInviteRequest) ProtoMessage() {}

func (x *AcceptInviteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workspace_workspace_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptInviteRequest.ProtoReflect.Descriptor instead.
func (*AcceptInviteRequest) Descriptor() ([]byte, []int) {
	return file_workspace_workspace_proto_rawDescGZIP(), []int{31}
}

func (x *AcceptInviteRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *AcceptInviteRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type AcceptInviteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Workspace     *Workspace             `protobuf:"bytes,1,opt,name=workspace,proto3" json:"workspace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcceptInviteResponse) Reset() {
	*x = AcceptInviteResponse{}
	mi := &file_workspace_workspace_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptInviteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptInviteResponse) ProtoMessage() {}

func (x *AcceptInviteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_workspace_workspace_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptInviteResponse.ProtoReflect.Descriptor instead.
func (*AcceptInviteResponse) Descriptor() ([]byte, []int) {
	return file_workspace_workspace_proto_rawDescGZIP(), []int{32}
}

func (x *AcceptInviteResponse) GetWorkspace() *Workspace {
	if x != nil {
		return x.Workspace
	}
	return nil
}

type DeclineInviteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeclineInviteRequest) Reset() {
	*x = DeclineInviteRequest{}
	mi := &file_workspace_workspace_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeclineInviteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeclineInviteRequest) ProtoMessage() {}

func (x *DeclineInviteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workspace_workspace_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeclineInviteRequest.ProtoReflect.Descriptor instead.
func (*DeclineInviteRequest) Descriptor() ([]byte, []int) {
	return file_workspace_workspace_proto_rawDescGZIP(), []int{33}
}

func (x *DeclineInviteRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type DeclineInviteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeclineInviteResponse) Reset() {
	*x = DeclineInviteResponse{}
	mi := &file_workspace_workspace_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeclineInviteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeclineInviteResponse) ProtoMessage() {}

func (x *DeclineInviteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_workspace_workspace_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeclineInviteResponse.ProtoReflect.Descriptor instead.
func (*DeclineInviteResponse) Descriptor() ([]byte, []int) {
	return file_workspace_workspace_proto_rawDescGZIP(), []int{34}
}

func (x *DeclineInviteResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_workspace_workspace_proto protoreflect.FileDescriptor

const file_workspace_workspace_proto_rawDesc = "" +
	"\n" +
	"\x19workspace/workspace.proto\x12\tworkspace\x1a\x12common/types.proto\"x\n" +
	"\bCategory\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04slug\x18\x02 \x01(\tR\x04slug\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x12\n" +
	"\x04icon\x18\x05 \x01(\tR\x04icon\"\xcc\x02\n" +
	"\tWorkspace\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04slug\x18\x03 \x01(\tR\x04slug\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x12\x19\n" +
	"\bowner_id\x18\x05 \x01(\tR\aownerId\x12\x1d\n" +
	"\n" +
	"avatar_url\x18\x06 \x01(\tR\tavatarUrl\x12 \n" +
	"\vdescription\x18\a \x01(\tR\vdescription\x123\n" +
	"\n" +
	"categories\x18\b \x03(\v2\x13.workspace.CategoryR\n" +
	"categories\x120\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x11.common.TimestampR\tcreatedAt\x120\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\v2\x11.common.TimestampR\tupdatedAt\"\xf2\x01\n" +
	"\x0fWorkspaceMember\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12!\n" +
	"\fworkspace_id\x18\x02 \x01(\tR\vworkspaceId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12\x12\n" +
	"\x04role\x18\x04 \x01(\tR\x04role\x12\x1d\n" +
	"\n" +
	"invited_by\x18\x05 \x01(\tR\tinvitedBy\x12.\n" +
	"\tjoined_at\x18\x06 \x01(\v2\x11.common.TimestampR\bjoinedAt\x120\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x11.common.TimestampR\tcreatedAt\"\x17\n" +
	"\x15ListCategoriesRequest\"M\n" +
	"\x16ListCategoriesResponse\x123\n" +
	"\n" +
	"categories\x18\x01 \x03(\v2\x13.workspace.CategoryR\n" +
	"categories\"a\n" +
	"\x1fCreatePersonalWorkspacesRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12%\n" +
	"\x0ecategory_slugs\x18\x02 \x03(\tR\rcategorySlugs\"X\n" +
	" CreatePersonalWorkspacesResponse\x124\n" +
	"\n" +
	"workspaces\x18\x01 \x03(\v2\x14.workspace.WorkspaceR\n" +
	"workspaces\"\x93\x01\n" +
	"\x19CreateOrgWorkspaceRequest\x12\x19\n" +
	"\bowner_id\x18\x01 \x01(\tR\aownerId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12%\n" +
	"\x0ecategory_slugs\x18\x04 \x03(\tR\rcategorySlugs\"P\n" +
	"\x1aCreateOrgWorkspaceResponse\x122\n" +
	"\tworkspace\x18\x01 \x01(\v2\x14.workspace.WorkspaceR\tworkspace\"8\n" +
	"\x13GetWorkspaceRequest\x12!\n" +
	"\fworkspace_id\x18\x01 \x01(\tR\vworkspaceId\"J\n" +
	"\x14GetWorkspaceResponse\x122\n" +
	"\tworkspace\x18\x01 \x01(\v2\x14.workspace.WorkspaceR\tworkspace\"4\n" +
	"\x19ListUserWorkspacesRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"v\n" +
	"\x1aListUserWorkspacesResponse\x120\n" +
	"\bpersonal\x18\x01 \x03(\v2\x14.workspace.WorkspaceR\bpersonal\x12&\n" +
	"\x03org\x18\x02 \x03(\v2\x14.workspace.WorkspaceR\x03org\"\x90\x01\n" +
	"\x16UpdateWorkspaceRequest\x12!\n" +
	"\fworkspace_id\x18\x01 \x01(\tR\vworkspaceId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"avatar_url\x18\x04 \x01(\tR\tavatarUrl\"M\n" +
	"\x17UpdateWorkspaceResponse\x122\n" +
	"\tworkspace\x18\x01 \x01(\v2\x14.workspace.WorkspaceR\tworkspace\"T\n" +
	"\x16DeleteWorkspaceRequest\x12!\n" +
	"\fworkspace_id\x18\x01 \x01(\tR\vworkspaceId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"3\n" +
	"\x17DeleteWorkspaceResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"_\n" +
	"\x15EnableCategoryRequest\x12!\n" +
	"\fworkspace_id\x18\x01 \x01(\tR\vworkspaceId\x12#\n" +
	"\rcategory_slug\x18\x02 \x01(\tR\fcategorySlug\"L\n" +
	"\x16EnableCategoryResponse\x122\n" +
	"\tworkspace\x18\x01 \x01(\v2\x14.workspace.WorkspaceR\tworkspace\"`\n" +
	"\x16DisableCategoryRequest\x12!\n" +
	"\fworkspace_id\x18\x01 \x01(\tR\vworkspaceId\x12#\n" +
	"\rcategory_slug\x18\x02 \x01(\tR\fcategorySlug\"M\n" +
	"\x17DisableCategoryResponse\x122\n" +
	"\tworkspace\x18\x01 \x01(\v2\x14.workspace.WorkspaceR\tworkspace\"\x81\x01\n" +
	"\x10AddMemberRequest\x12!\n" +
	"\fworkspace_id\x18\x01 \x01(\tR\vworkspaceId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x12\n" +
	"\x04role\x18\x03 \x01(\tR\x04role\x12\x1d\n" +
	"\n" +
	"invited_by\x18\x04 \x01(\tR\tinvitedBy\"G\n" +
	"\x11AddMemberResponse\x122\n" +
	"\x06member\x18\x01 \x01(\v2\x1a.workspace.WorkspaceMemberR\x06member\"Q\n" +
	"\x13RemoveMemberRequest\x12!\n" +
	"\fworkspace_id\x18\x01 \x01(\tR\vworkspaceId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"0\n" +
	"\x14RemoveMemberResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"i\n" +
	"\x17UpdateMemberRoleRequest\x12!\n" +
	"\fworkspace_id\x18\x01 \x01(\tR\vworkspaceId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x12\n" +
	"\x04role\x18\x03 \x01(\tR\x04role\"N\n" +
	"\x18UpdateMemberRoleResponse\x122\n" +
	"\x06member\x18\x01 \x01(\v2\x1a.workspace.WorkspaceMemberR\x06member\"7\n" +
	"\x12ListMembersRequest\x12!\n" +
	"\fworkspace_id\x18\x01 \x01(\tR\vworkspaceId\"K\n" +
	"\x13ListMembersResponse\x124\n" +
	"\amembers\x18\x01 \x03(\v2\x1a.workspace.WorkspaceMemberR\amembers\"\x81\x01\n" +
	"\x13InviteMemberRequest\x12!\n" +
	"\fworkspace_id\x18\x01 \x01(\tR\vworkspaceId\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x12\n" +
	"\x04role\x18\x03 \x01(\tR\x04role\x12\x1d\n" +
	"\n" +
	"invited_by\x18\x04 \x01(\tR\tinvitedBy\"9\n" +
	"\x14InviteMemberResponse\x12!\n" +
	"\finvite_token\x18\x01 \x01(\tR\vinviteToken\"D\n" +
	"\x13AcceptInviteRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"J\n" +
	"\x14AcceptInviteResponse\x122\n" +
	"\tworkspace\x18\x01 \x01(\v2\x14.workspace.WorkspaceR\tworkspace\",\n" +
	"\x14DeclineInviteRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"1\n" +
	"\x15DeclineInviteResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\x94\v\n" +
	"\x10WorkspaceService\x12U\n" +
	"\x0eListCategories\x12 .workspace.ListCategoriesRequest\x1a!.workspace.ListCategoriesResponse\x12s\n" +
	"\x18CreatePersonalWorkspaces\x12*.workspace.CreatePersonalWorkspacesRequest\x1a+.workspace.CreatePersonalWorkspacesResponse\x12a\n" +
	"\x12CreateOrgWorkspace\x12$.workspace.CreateOrgWorkspaceRequest\x1a%.workspace.CreateOrgWorkspaceResponse\x12O\n" +
	"\fGetWorkspace\x12\x1e.workspace.GetWorkspaceRequest\x1a\x1f.workspace.GetWorkspaceResponse\x12a\n" +
	"\x12ListUserWorkspaces\x12$.workspace.ListUserWorkspacesRequest\x1a%.workspace.ListUserWorkspacesResponse\x12X\n" +
	"\x0fUpdateWorkspace\x12!.workspace.UpdateWorkspaceRequest\x1a\".workspace.UpdateWorkspaceResponse\x12X\n" +
	"\x0fDeleteWorkspace\x12!.workspace.DeleteWorkspaceRequest\x1a\".workspace.DeleteWorkspaceResponse\x12U\n" +
	"\x0eEnableCategory\x12 .workspace.EnableCategoryRequest\x1a!.workspace.EnableCategoryResponse\x12X\n" +
	"\x0fDisableCategory\x12!.workspace.DisableCategoryRequest\x1a\".workspace.DisableCategoryResponse\x12F\n" +
	"\tAddMember\x12\x1b.workspace.AddMemberRequest\x1a\x1c.workspace.AddMemberResponse\x12O\n" +
	"\fRemoveMember\x12\x1e.workspace.RemoveMemberRequest\x1a\x1f.workspace.RemoveMemberResponse\x12[\n" +
	"\x10UpdateMemberRole\x12\".workspace.UpdateMemberRoleRequest\x1a#.workspace.UpdateMemberRoleResponse\x12L\n" +
	"\vListMembers\x12\x1d.workspace.ListMembersRequest\x1a\x1e.workspace.ListMembersResponse\x12O\n" +
	"\fInviteMember\x12\x1e.workspace.InviteMemberRequest\x1a\x1f.workspace.InviteMemberResponse\x12O\n" +
	"\fAcceptInvite\x12\x1e.workspace.AcceptInviteRequest\x1a\x1f.workspace.AcceptInviteResponse\x12R\n" +
	"\rDeclineInvite\x12\x1f.workspace.DeclineInviteRequest\x1a .workspace.DeclineInviteResponseB&Z$inkwell/server/pkg/grpc/workspaceb\x06proto3"

var (
	file_workspace_workspace_proto_rawDescOnce sync.Once
	file_workspace_workspace_proto_rawDescData []byte
)

func file_workspace_workspace_proto_rawDescGZIP() []byte {
	file_workspace_workspace_proto_rawDescOnce.Do(func() {
		file_workspace_workspace_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_workspace_workspace_proto_rawDesc), len(file_workspace_workspace_proto_rawDesc)))
	})
	return file_workspace_workspace_proto_rawDescData
}

var file_workspace_workspace_proto_msgTypes = make([]protoimpl.MessageInfo, 35)
var file_workspace_workspace_proto_goTypes = []any{
	(*Category)(nil),                         // 0: workspace.Category
	(*Workspace)(nil),                        // 1: workspace.Workspace
	(*WorkspaceMember)(nil),                  // 2: workspace.WorkspaceMember
	(*ListCategoriesRequest)(nil),            // 3: workspace.ListCategoriesRequest
	(*ListCategoriesResponse)(nil),           // 4: workspace.ListCategoriesResponse
	(*CreatePersonalWorkspacesRequest)(nil),  // 5: workspace.CreatePersonalWorkspacesRequest
	(*CreatePersonalWorkspacesResponse)(nil), // 6: workspace.CreatePersonalWorkspacesResponse
	(*CreateOrgWorkspaceRequest)(nil),        // 7: workspace.CreateOrgWorkspaceRequest
	(*CreateOrgWorkspaceResponse)(nil),       // 8: workspace.CreateOrgWorkspaceResponse
	(*GetWorkspaceRequest)(nil),              // 9: workspace.GetWorkspaceRequest
	(*GetWorkspaceResponse)(nil),             // 10: workspace.GetWorkspaceResponse
	(*ListUserWorkspacesRequest)(nil),        // 11: workspace.ListUserWorkspacesRequest
	(*ListUserWorkspacesResponse)(nil),       // 12: workspace.ListUserWorkspacesResponse
	(*UpdateWorkspaceRequest)(nil),           // 13: workspace.UpdateWorkspaceRequest
	(*UpdateWorkspaceResponse)(nil),          // 14: workspace.UpdateWorkspaceResponse
	(*DeleteWorkspaceRequest)(nil),           // 15: workspace.DeleteWorkspaceRequest
	(*DeleteWorkspaceResponse)(nil),          // 16: workspace.DeleteWorkspaceResponse
	(*EnableCategoryRequest)(nil),            // 17: workspace.EnableCategoryRequest
	(*EnableCategoryResponse)(nil),           // 18: workspace.EnableCategoryResponse
	(*DisableCategoryRequest)(nil),           // 19: workspace.DisableCategoryRequest
	(*DisableCategoryResponse)(nil),          // 20: workspace.DisableCategoryResponse
	(*AddMemberRequest)(nil),                 // 21: workspace.AddMemberRequest
	(*AddMemberResponse)(nil),                // 22: workspace.AddMemberResponse
	(*RemoveMemberRequest)(nil),              // 23: workspace.RemoveMemberRequest
	(*RemoveMemberResponse)(nil),             // 24: workspace.RemoveMemberResponse
	(*UpdateMemberRoleRequest)(nil),          // 25: workspace.UpdateMemberRoleRequest
	(*UpdateMemberRoleResponse)(nil),         // 26: workspace.UpdateMemberRoleResponse
	(*ListMembersRequest)(nil),               // 27: workspace.ListMembersRequest
	(*ListMembersResponse)(nil),              // 28: workspace.ListMembersResponse
	(*InviteMemberRequest)(nil),              // 29: workspace.InviteMemberRequest
	(*InviteMemberResponse)(nil),             // 30: workspace.InviteMemberResponse
	(*AcceptInviteRequest)(nil),              // 31: workspace.AcceptInviteRequest
	(*AcceptInviteResponse)(nil),             // 32: workspace.AcceptInviteResponse
	(*DeclineInviteRequest)(nil),             // 33: workspace.DeclineInviteRequest
	(*DeclineInviteResponse)(nil),            // 34: workspace.DeclineInviteResponse
	(*common.Timestamp)(nil),                 // 35: common.Timestamp
}
var file_workspace_workspace_proto_depIdxs = []int32{
	0,  // 0: workspace.Workspace.categories:type_name -> workspace.Category
	35, // 1: workspace.Workspace.created_at:type_name -> common.Timestamp
	35, // 2: workspace.Workspace.updated_at:type_name -> common.Timestamp
	35, // 3: workspace.WorkspaceMember.joined_at:type_name -> common.Timestamp
	35, // 4: workspace.WorkspaceMember.created_at:type_name -> common.Timestamp
	0,  // 5: workspace.ListCategoriesResponse.categories:type_name -> workspace.Category
	1,  // 6: workspace.CreatePersonalWorkspacesResponse.workspaces:type_name -> workspace.Workspace
	1,  // 7: workspace.CreateOrgWorkspaceResponse.workspace:type_name -> workspace.Workspace
	1,  // 8: workspace.GetWorkspaceResponse.workspace:type_name -> workspace.Workspace
	1,  // 9: workspace.ListUserWorkspacesResponse.personal:type_name -> workspace.Workspace
	1,  // 10: workspace.ListUserWorkspacesResponse.org:type_name -> workspace.Workspace
	1,  // 11: workspace.UpdateWorkspaceResponse.workspace:type_name -> workspace.Workspace
	1,  // 12: workspace.EnableCategoryResponse.workspace:type_name -> workspace.Workspace
	1,  // 13: workspace.DisableCategoryResponse.workspace:type_name -> workspace.Workspace
	2,  // 14: workspace.AddMemberResponse.member:type_name -> workspace.WorkspaceMember
	2,  // 15: workspace.UpdateMemberRoleResponse.member:type_name -> workspace.WorkspaceMember
	2,  // 16: workspace.ListMembersResponse.members:type_name -> workspace.WorkspaceMember
	1,  // 17: workspace.AcceptInviteResponse.workspace:type_name -> workspace.Workspace
	3,  // 18: workspace.WorkspaceService.ListCategories:input_type -> workspace.ListCategoriesRequest
	5,  // 19: workspace.WorkspaceService.CreatePersonalWorkspaces:input_type -> workspace.CreatePersonalWorkspacesRequest
	7,  // 20: workspace.WorkspaceService.CreateOrgWorkspace:input_type -> workspace.CreateOrgWorkspaceRequest
	9,  // 21: workspace.WorkspaceService.GetWorkspace:input_type -> workspace.GetWorkspaceRequest
	11, // 22: workspace.WorkspaceService.ListUserWorkspaces:input_type -> workspace.ListUserWorkspacesRequest
	13, // 23: workspace.WorkspaceService.UpdateWorkspace:input_type -> workspace.UpdateWorkspaceRequest
	15, // 24: workspace.WorkspaceService.DeleteWorkspace:input_type -> workspace.DeleteWorkspaceRequest
	17, // 25: workspace.WorkspaceService.EnableCategory:input_type -> workspace.EnableCategoryRequest
	19, // 26: workspace.WorkspaceService.DisableCategory:input_type -> workspace.DisableCategoryRequest
	21, // 27: workspace.WorkspaceService.AddMember:input_type -> workspace.AddMemberRequest
	23, // 28: workspace.WorkspaceService.RemoveMember:input_type -> workspace.RemoveMemberRequest
	25, // 29: workspace.WorkspaceService.UpdateMemberRole:input_type -> workspace.UpdateMemberRoleRequest
	27, // 30: workspace.WorkspaceService.ListMembers:input_type -> workspace.ListMembersRequest
	29, // 31: workspace.WorkspaceService.InviteMember:input_type -> workspace.InviteMemberRequest
	31, // 32: workspace.WorkspaceService.AcceptInvite:input_type -> workspace.AcceptInviteRequest
	33, // 33: workspace.WorkspaceService.DeclineInvite:input_type -> workspace.DeclineInviteRequest
	4,  // 34: workspace.WorkspaceService.ListCategories:output_type -> workspace.ListCategoriesResponse
	6,  // 35: workspace.WorkspaceService.CreatePersonalWorkspaces:output_type -> workspace.CreatePersonalWorkspacesResponse
	8,  // 36: workspace.WorkspaceService.CreateOrgWorkspace:output_type -> workspace.CreateOrgWorkspaceResponse
	10, // 37: workspace.WorkspaceService.GetWorkspace:output_type -> workspace.GetWorkspaceResponse
	12, // 38: workspace.WorkspaceService.ListUserWorkspaces:output_type -> workspace.ListUserWorkspacesResponse
	14, // 39: workspace.WorkspaceService.UpdateWorkspace:output_type -> workspace.UpdateWorkspaceResponse
	16, // 40: workspace.WorkspaceService.DeleteWorkspace:output_type -> workspace.DeleteWorkspaceResponse
	18, // 41: workspace.WorkspaceService.EnableCategory:output_type -> workspace.EnableCategoryResponse
	20, // 42: workspace.WorkspaceService.DisableCategory:output_type -> workspace.DisableCategoryResponse
	22, // 43: workspace.WorkspaceService.AddMember:output_type -> workspace.AddMemberResponse
	24, // 44: workspace.WorkspaceService.RemoveMember:output_type -> workspace.RemoveMemberResponse
	26, // 45: workspace.WorkspaceService.UpdateMemberRole:output_type -> workspace.UpdateMemberRoleResponse
	28, // 46: workspace.WorkspaceService.ListMembers:output_type -> workspace.ListMembersResponse
	30, // 47: workspace.WorkspaceService.InviteMember:output_type -> workspace.InviteMemberResponse
	32, // 48: workspace.WorkspaceService.AcceptInvite:output_type -> workspace.AcceptInviteResponse
	34, // 49: workspace.WorkspaceService.DeclineInvite:output_type -> workspace.DeclineInviteResponse
	34, // [34:50] is the sub-list for method output_type
	18, // [18:34] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_workspace_workspace_proto_init() }
func file_workspace_workspace_proto_init() {
	if File_workspace_workspace_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_workspace_workspace_proto_rawDesc), len(file_workspace_workspace_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   35,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_workspace_workspace_proto_goTypes,
		DependencyIndexes: file_workspace_workspace_proto_depIdxs,
		MessageInfos:      file_workspace_workspace_proto_msgTypes,
	}.Build()
	File_workspace_workspace_proto = out.File
	file_workspace_workspace_proto_goTypes = nil
	file_workspace_workspace_proto_depIdxs = nil
}
