// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v4.25.1
// source: billing/billing.proto

package billing

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BillingService_GetPlans_FullMethodName              = "/billing.BillingService/GetPlans"
	BillingService_GetPlan_FullMethodName               = "/billing.BillingService/GetPlan"
	BillingService_GetEffectiveTier_FullMethodName      = "/billing.BillingService/GetEffectiveTier"
	BillingService_ListAllTiers_FullMethodName          = "/billing.BillingService/ListAllTiers"
	BillingService_CreateTier_FullMethodName            = "/billing.BillingService/CreateTier"
	BillingService_UpdateTier_FullMethodName            = "/billing.BillingService/UpdateTier"
	BillingService_DeleteTier_FullMethodName            = "/billing.BillingService/DeleteTier"
	BillingService_ReorderTiers_FullMethodName          = "/billing.BillingService/ReorderTiers"
	BillingService_ListGateways_FullMethodName          = "/billing.BillingService/ListGateways"
	BillingService_CreateSubscription_FullMethodName    = "/billing.BillingService/CreateSubscription"
	BillingService_GetUserSubscription_FullMethodName   = "/billing.BillingService/GetUserSubscription"
	BillingService_UpdateSubscription_FullMethodName    = "/billing.BillingService/UpdateSubscription"
	BillingService_CancelSubscription_FullMethodName    = "/billing.BillingService/CancelSubscription"
	BillingService_AddPaymentMethod_FullMethodName      = "/billing.BillingService/AddPaymentMethod"
	BillingService_GetUserPaymentMethods_FullMethodName = "/billing.BillingService/GetUserPaymentMethods"
	BillingService_DeletePaymentMethod_FullMethodName   = "/billing.BillingService/DeletePaymentMethod"
	BillingService_GetUserInvoices_FullMethodName       = "/billing.BillingService/GetUserInvoices"
	BillingService_GetInvoice_FullMethodName            = "/billing.BillingService/GetInvoice"
	BillingService_TrackUsage_FullMethodName            = "/billing.BillingService/TrackUsage"
	BillingService_GetUserUsage_FullMethodName          = "/billing.BillingService/GetUserUsage"
	BillingService_ProcessWebhook_FullMethodName        = "/billing.BillingService/ProcessWebhook"
	BillingService_GetBillingAnalytics_FullMethodName   = "/billing.BillingService/GetBillingAnalytics"
	BillingService_ListAllSubscriptions_FullMethodName  = "/billing.BillingService/ListAllSubscriptions"
)

// BillingServiceClient is the client API for BillingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Billing service definition
type BillingServiceClient interface {
	// Plan management
	GetPlans(ctx context.Context, in *GetPlansRequest, opts ...grpc.CallOption) (*GetPlansResponse, error)
	GetPlan(ctx context.Context, in *GetPlanRequest, opts ...grpc.CallOption) (*GetPlanResponse, error)
	// GetEffectiveTier returns the tier whose limits apply to a user (their
	// subscription's tier, or the default tier). Used by quota enforcement.
	GetEffectiveTier(ctx context.Context, in *GetEffectiveTierRequest, opts ...grpc.CallOption) (*GetEffectiveTierResponse, error)
	// Admin tier management (Settings → Admin → Billing tier editor).
	ListAllTiers(ctx context.Context, in *ListAllTiersRequest, opts ...grpc.CallOption) (*ListAllTiersResponse, error)
	CreateTier(ctx context.Context, in *CreateTierRequest, opts ...grpc.CallOption) (*CreateTierResponse, error)
	UpdateTier(ctx context.Context, in *UpdateTierRequest, opts ...grpc.CallOption) (*UpdateTierResponse, error)
	DeleteTier(ctx context.Context, in *DeleteTierRequest, opts ...grpc.CallOption) (*DeleteTierResponse, error)
	ReorderTiers(ctx context.Context, in *ReorderTiersRequest, opts ...grpc.CallOption) (*ReorderTiersResponse, error)
	// Payment gateways (admin)
	ListGateways(ctx context.Context, in *ListGatewaysRequest, opts ...grpc.CallOption) (*ListGatewaysResponse, error)
	// Subscription management
	CreateSubscription(ctx context.Context, in *CreateSubscriptionRequest, opts ...grpc.CallOption) (*CreateSubscriptionResponse, error)
	GetUserSubscription(ctx context.Context, in *GetUserSubscriptionRequest, opts ...grpc.CallOption) (*GetUserSubscriptionResponse, error)
	UpdateSubscription(ctx context.Context, in *UpdateSubscriptionRequest, opts ...grpc.CallOption) (*UpdateSubscriptionResponse, error)
	CancelSubscription(ctx context.Context, in *CancelSubscriptionRequest, opts ...grpc.CallOption) (*CancelSubscriptionResponse, error)
	// Payment method management
	AddPaymentMethod(ctx context.Context, in *AddPaymentMethodRequest, opts ...grpc.CallOption) (*AddPaymentMethodResponse, error)
	GetUserPaymentMethods(ctx context.Context, in *GetUserPaymentMethodsRequest, opts ...grpc.CallOption) (*GetUserPaymentMethodsResponse, error)
	DeletePaymentMethod(ctx context.Context, in *DeletePaymentMethodRequest, opts ...grpc.CallOption) (*DeletePaymentMethodResponse, error)
	// Invoice management
	GetUserInvoices(ctx context.Context, in *GetUserInvoicesRequest, opts ...grpc.CallOption) (*GetUserInvoicesResponse, error)
	GetInvoice(ctx context.Context, in *GetInvoiceRequest, opts ...grpc.CallOption) (*GetInvoiceResponse, error)
	// Usage tracking
	TrackUsage(ctx context.Context, in *TrackUsageRequest, opts ...grpc.CallOption) (*TrackUsageResponse, error)
	GetUserUsage(ctx context.Context, in *GetUserUsageRequest, opts ...grpc.CallOption) (*GetUserUsageResponse, error)
	// Webhook processing
	ProcessWebhook(ctx context.Context, in *ProcessWebhookRequest, opts ...grpc.CallOption) (*ProcessWebhookResponse, error)
	// Admin analytics — MRR, ARR, churn, tier distribution. Callers must have the
	// admin role; enforcement lives in the gateway.
	GetBillingAnalytics(ctx context.Context, in *GetBillingAnalyticsRequest, opts ...grpc.CallOption) (*GetBillingAnalyticsResponse, error)
	// Admin listing of every subscription across all users.
	ListAllSubscriptions(ctx context.Context, in *ListAllSubscriptionsRequest, opts ...grpc.CallOption) (*ListAllSubscriptionsResponse, error)
}

type billingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBillingServiceClient(cc grpc.ClientConnInterface) BillingServiceClient {
	return &billingServiceClient{cc}
}

func (c *billingServiceClient) GetPlans(ctx context.Context, in *GetPlansRequest, opts ...grpc.CallOption) (*GetPlansResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPlansResponse)
	err := c.cc.Invoke(ctx, BillingService_GetPlans_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *billingServiceClient) GetPlan(ctx context.Context, in *GetPlanRequest, opts ...grpc.CallOption) (*GetPlanResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPlanResponse)
	err := c.cc.Invoke(ctx, BillingService_GetPlan_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *billingServiceClient) GetEffectiveTier(ctx context.Context, in *GetEffectiveTierRequest, opts ...grpc.CallOption) (*GetEffectiveTierResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetEffectiveTierResponse)
	err := c.cc.Invoke(ctx, BillingService_GetEffectiveTier_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *billingServiceClient) ListAllTiers(ctx context.Context, in *ListAllTiersRequest, opts ...grpc.CallOption) (*ListAllTiersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAllTiersResponse)
	err := c.cc.Invoke(ctx, BillingService_ListAllTiers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *billingServiceClient) CreateTier(ctx context.Context, in *CreateTierRequest, opts ...grpc.CallOption) (*CreateTierResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateTierResponse)
	err := c.cc.Invoke(ctx, BillingService_CreateTier_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *billingServiceClient) UpdateTier(ctx context.Context, in *UpdateTierRequest, opts ...grpc.CallOption) (*UpdateTierResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateTierResponse)
	err := c.cc.Invoke(ctx, BillingService_UpdateTier_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *billingServiceClient) DeleteTier(ctx context.Context, in *DeleteTierRequest, opts ...grpc.CallOption) (*DeleteTierResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteTierResponse)
	err := c.cc.Invoke(ctx, BillingService_DeleteTier_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *billingServiceClient) ReorderTiers(ctx context.Context, in *ReorderTiersRequest, opts ...grpc.CallOption) (*ReorderTiersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReorderTiersResponse)
	err := c.cc.Invoke(ctx, BillingService_ReorderTiers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *billingServiceClient) ListGateways(ctx context.Context, in *ListGatewaysRequest, opts ...grpc.CallOption) (*ListGatewaysResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListGatewaysResponse)
	err := c.cc.Invoke(ctx, BillingService_ListGateways_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *billingServiceClient) CreateSubscription(ctx context.Context, in *CreateSubscriptionRequest, opts ...grpc.CallOption) (*CreateSubscriptionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateSubscriptionResponse)
	err := c.cc.Invoke(ctx, BillingService_CreateSubscription_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *billingServiceClient) GetUserSubscription(ctx context.Context, in *GetUserSubscriptionRequest, opts ...grpc.CallOption) (*GetUserSubscriptionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserSubscriptionResponse)
	err := c.cc.Invoke(ctx, BillingService_GetUserSubscription_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *billingServiceClient) UpdateSubscription(ctx context.Context, in *UpdateSubscriptionRequest, opts ...grpc.CallOption) (*UpdateSubscriptionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateSubscriptionResponse)
	err := c.cc.Invoke(ctx, BillingService_UpdateSubscription_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *billingServiceClient) CancelSubscription(ctx context.Context, in *CancelSubscriptionRequest, opts ...grpc.CallOption) (*CancelSubscriptionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancelSubscriptionResponse)
	err := c.cc.Invoke(ctx, BillingService_CancelSubscription_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *billingServiceClient) AddPaymentMethod(ctx context.Context, in *AddPaymentMethodRequest, opts ...grpc.CallOption) (*AddPaymentMethodResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddPaymentMethodResponse)
	err := c.cc.Invoke(ctx, BillingService_AddPaymentMethod_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *billingServiceClient) GetUserPaymentMethods(ctx context.Context, in *GetUserPaymentMethodsRequest, opts ...grpc.CallOption) (*GetUserPaymentMethodsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserPaymentMethodsResponse)
	err := c.cc.Invoke(ctx, BillingService_GetUserPaymentMethods_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *billingServiceClient) DeletePaymentMethod(ctx context.Context, in *DeletePaymentMethodRequest, opts ...grpc.CallOption) (*DeletePaymentMethodResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeletePaymentMethodResponse)
	err := c.cc.Invoke(ctx, BillingService_DeletePaymentMethod_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *billingServiceClient) GetUserInvoices(ctx context.Context, in *GetUserInvoicesRequest, opts ...grpc.CallOption) (*GetUserInvoicesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserInvoicesResponse)
	err := c.cc.Invoke(ctx, BillingService_GetUserInvoices_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *billingServiceClient) GetInvoice(ctx context.Context, in *GetInvoiceRequest, opts ...grpc.CallOption) (*GetInvoiceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetInvoiceResponse)
	err := c.cc.Invoke(ctx, BillingService_GetInvoice_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *billingServiceClient) TrackUsage(ctx context.Context, in *TrackUsageRequest, opts ...grpc.CallOption) (*TrackUsageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TrackUsageResponse)
	err := c.cc.Invoke(ctx, BillingService_TrackUsage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *billingServiceClient) GetUserUsage(ctx context.Context, in *GetUserUsageRequest, opts ...grpc.CallOption) (*GetUserUsageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserUsageResponse)
	err := c.cc.Invoke(ctx, BillingService_GetUserUsage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *billingServiceClient) ProcessWebhook(ctx context.Context, in *ProcessWebhookRequest, opts ...grpc.CallOption) (*ProcessWebhookResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProcessWebhookResponse)
	err := c.cc.Invoke(ctx, BillingService_ProcessWebhook_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *billingServiceClient) GetBillingAnalytics(ctx context.Context, in *GetBillingAnalyticsRequest, opts ...grpc.CallOption) (*GetBillingAnalyticsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBillingAnalyticsResponse)
	err := c.cc.Invoke(ctx, BillingService_GetBillingAnalytics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *billingServiceClient) ListAllSubscriptions(ctx context.Context, in *ListAllSubscriptionsRequest, opts ...grpc.CallOption) (*ListAllSubscriptionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAllSubscriptionsResponse)
	err := c.cc.Invoke(ctx, BillingService_ListAllSubscriptions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BillingServiceServer is the server API for BillingService service.
// All implementations must embed UnimplementedBillingServiceServer
// for forward compatibility.
//
// Billing service definition
type BillingServiceServer interface {
	// Plan management
	GetPlans(context.Context, *GetPlansRequest) (*GetPlansResponse, error)
	GetPlan(context.Context, *GetPlanRequest) (*GetPlanResponse, error)
	// GetEffectiveTier returns the tier whose limits apply to a user (their
	// subscription's tier, or the default tier). Used by quota enforcement.
	GetEffectiveTier(context.Context, *GetEffectiveTierRequest) (*GetEffectiveTierResponse, error)
	// Admin tier management (Settings → Admin → Billing tier editor).
	ListAllTiers(context.Context, *ListAllTiersRequest) (*ListAllTiersResponse, error)
	CreateTier(context.Context, *CreateTierRequest) (*CreateTierResponse, error)
	UpdateTier(context.Context, *UpdateTierRequest) (*UpdateTierResponse, error)
	DeleteTier(context.Context, *DeleteTierRequest) (*DeleteTierResponse, error)
	ReorderTiers(context.Context, *ReorderTiersRequest) (*ReorderTiersResponse, error)
	// Payment gateways (admin)
	ListGateways(context.Context, *ListGatewaysRequest) (*ListGatewaysResponse, error)
	// Subscription management
	CreateSubscription(context.Context, *CreateSubscriptionRequest) (*CreateSubscriptionResponse, error)
	GetUserSubscription(context.Context, *GetUserSubscriptionRequest) (*GetUserSubscriptionResponse, error)
	UpdateSubscription(context.Context, *UpdateSubscriptionRequest) (*UpdateSubscriptionResponse, error)
	CancelSubscription(context.Context, *CancelSubscriptionRequest) (*CancelSubscriptionResponse, error)
	// Payment method management
	AddPaymentMethod(context.Context, *AddPaymentMethodRequest) (*AddPaymentMethodResponse, error)
	GetUserPaymentMethods(context.Context, *GetUserPaymentMethodsRequest) (*GetUserPaymentMethodsResponse, error)
	DeletePaymentMethod(context.Context, *DeletePaymentMethodRequest) (*DeletePaymentMethodResponse, error)
	// Invoice management
	GetUserInvoices(context.Context, *GetUserInvoicesRequest) (*GetUserInvoicesResponse, error)
	GetInvoice(context.Context, *GetInvoiceRequest) (*GetInvoiceResponse, error)
	// Usage tracking
	TrackUsage(context.Context, *TrackUsageRequest) (*TrackUsageResponse, error)
	GetUserUsage(context.Context, *GetUserUsageRequest) (*GetUserUsageResponse, error)
	// Webhook processing
	ProcessWebhook(context.Context, *ProcessWebhookRequest) (*ProcessWebhookResponse, error)
	// Admin analytics — MRR, ARR, churn, tier distribution. Callers must have the
	// admin role; enforcement lives in the gateway.
	GetBillingAnalytics(context.Context, *GetBillingAnalyticsRequest) (*GetBillingAnalyticsResponse, error)
	// Admin listing of every subscription across all users.
	ListAllSubscriptions(context.Context, *ListAllSubscriptionsRequest) (*ListAllSubscriptionsResponse, error)
	mustEmbedUnimplementedBillingServiceServer()
}

// UnimplementedBillingServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBillingServiceServer struct{}

func (UnimplementedBillingServiceServer) GetPlans(context.Context, *GetPlansRequest) (*GetPlansResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPlans not implemented")
}
func (UnimplementedBillingServiceServer) GetPlan(context.Context, *GetPlanRequest) (*GetPlanResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPlan not implemented")
}
func (UnimplementedBillingServiceServer) GetEffectiveTier(context.Context, *GetEffectiveTierRequest) (*GetEffectiveTierResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetEffectiveTier not implemented")
}
func (UnimplementedBillingServiceServer) ListAllTiers(context.Context, *ListAllTiersRequest) (*ListAllTiersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListAllTiers not implemented")
}
func (UnimplementedBillingServiceServer) CreateTier(context.Context, *CreateTierRequest) (*CreateTierResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateTier not implemented")
}
func (UnimplementedBillingServiceServer) UpdateTier(context.Context, *UpdateTierRequest) (*UpdateTierResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateTier not implemented")
}
func (UnimplementedBillingServiceServer) DeleteTier(context.Context, *DeleteTierRequest) (*DeleteTierResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteTier not implemented")
}
func (UnimplementedBillingServiceServer) ReorderTiers(context.Context, *ReorderTiersRequest) (*ReorderTiersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReorderTiers not implemented")
}
func (UnimplementedBillingServiceServer) ListGateways(context.Context, *ListGatewaysRequest) (*ListGatewaysResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListGateways not implemented")
}
func (UnimplementedBillingServiceServer) CreateSubscription(context.Context, *CreateSubscriptionRequest) (*CreateSubscriptionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateSubscription not implemented")
}
func (UnimplementedBillingServiceServer) GetUserSubscription(context.Context, *GetUserSubscriptionRequest) (*GetUserSubscriptionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserSubscription not implemented")
}
func (UnimplementedBillingServiceServer) UpdateSubscription(context.Context, *UpdateSubscriptionRequest) (*UpdateSubscriptionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateSubscription not implemented")
}
func (UnimplementedBillingServiceServer) CancelSubscription(context.Context, *CancelSubscriptionRequest) (*CancelSubscriptionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CancelSubscription not implemented")
}
func (UnimplementedBillingServiceServer) AddPaymentMethod(context.Context, *AddPaymentMethodRequest) (*AddPaymentMethodResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddPaymentMethod not implemented")
}
func (UnimplementedBillingServiceServer) GetUserPaymentMethods(context.Context, *GetUserPaymentMethodsRequest) (*GetUserPaymentMethodsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserPaymentMethods not implemented")
}
func (UnimplementedBillingServiceServer) DeletePaymentMethod(context.Context, *DeletePaymentMethodRequest) (*DeletePaymentMethodResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeletePaymentMethod not implemented")
}
func (UnimplementedBillingServiceServer) GetUserInvoices(context.Context, *GetUserInvoicesRequest) (*GetUserInvoicesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserInvoices not implemented")
}
func (UnimplementedBillingServiceServer) GetInvoice(context.Context, *GetInvoiceRequest) (*GetInvoiceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetInvoice not implemented")
}
func (UnimplementedBillingServiceServer) TrackUsage(context.Context, *TrackUsageRequest) (*TrackUsageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TrackUsage not implemented")
}
func (UnimplementedBillingServiceServer) GetUserUsage(context.Context, *GetUserUsageRequest) (*GetUserUsageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserUsage not implemented")
}
func (UnimplementedBillingServiceServer) ProcessWebhook(context.Context, *ProcessWebhookRequest) (*ProcessWebhookResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ProcessWebhook not implemented")
}
func (UnimplementedBillingServiceServer) GetBillingAnalytics(context.Context, *GetBillingAnalyticsRequest) (*GetBillingAnalyticsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBillingAnalytics not implemented")
}
func (UnimplementedBillingServiceServer) ListAllSubscriptions(context.Context, *ListAllSubscriptionsRequest) (*ListAllSubscriptionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListAllSubscriptions not implemented")
}
func (UnimplementedBillingServiceServer) mustEmbedUnimplementedBillingServiceServer() {}
func (UnimplementedBillingServiceServer) testEmbeddedByValue()                        {}

// UnsafeBillingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BillingServiceServer will
// result in compilation errors.
type UnsafeBillingServiceServer interface {
	mustEmbedUnimplementedBillingServiceServer()
}

func RegisterBillingServiceServer(s grpc.ServiceRegistrar, srv BillingServiceServer) {
	// If the following call panics, it indicates UnimplementedBillingServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BillingService_ServiceDesc, srv)
}

func _BillingService_GetPlans_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPlansRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BillingServiceServer).GetPlans(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BillingService_GetPlans_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BillingServiceServer).GetPlans(ctx, req.(*GetPlansRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BillingService_GetPlan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPlanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BillingServiceServer).GetPlan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BillingService_GetPlan_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BillingServiceServer).GetPlan(ctx, req.(*GetPlanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BillingService_GetEffectiveTier_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEffectiveTierRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BillingServiceServer).GetEffectiveTier(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BillingService_GetEffectiveTier_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BillingServiceServer).GetEffectiveTier(ctx, req.(*GetEffectiveTierRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BillingService_ListAllTiers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAllTiersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BillingServiceServer).ListAllTiers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BillingService_ListAllTiers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BillingServiceServer).ListAllTiers(ctx, req.(*ListAllTiersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BillingService_CreateTier_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTierRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BillingServiceServer).CreateTier(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BillingService_CreateTier_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BillingServiceServer).CreateTier(ctx, req.(*CreateTierRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BillingService_UpdateTier_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTierRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BillingServiceServer).UpdateTier(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BillingService_UpdateTier_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BillingServiceServer).UpdateTier(ctx, req.(*UpdateTierRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BillingService_DeleteTier_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteTierRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BillingServiceServer).DeleteTier(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BillingService_DeleteTier_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BillingServiceServer).DeleteTier(ctx, req.(*DeleteTierRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BillingService_ReorderTiers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReorderTiersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BillingServiceServer).ReorderTiers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BillingService_ReorderTiers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BillingServiceServer).ReorderTiers(ctx, req.(*ReorderTiersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BillingService_ListGateways_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListGatewaysRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BillingServiceServer).ListGateways(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BillingService_ListGateways_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BillingServiceServer).ListGateways(ctx, req.(*ListGatewaysRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BillingService_CreateSubscription_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSubscriptionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BillingServiceServer).CreateSubscription(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BillingService_CreateSubscription_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BillingServiceServer).CreateSubscription(ctx, req.(*CreateSubscriptionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BillingService_GetUserSubscription_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserSubscriptionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BillingServiceServer).GetUserSubscription(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BillingService_GetUserSubscription_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BillingServiceServer).GetUserSubscription(ctx, req.(*GetUserSubscriptionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BillingService_UpdateSubscription_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateSubscriptionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BillingServiceServer).UpdateSubscription(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BillingService_UpdateSubscription_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BillingServiceServer).UpdateSubscription(ctx, req.(*UpdateSubscriptionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BillingService_CancelSubscription_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelSubscriptionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BillingServiceServer).CancelSubscription(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BillingService_CancelSubscription_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BillingServiceServer).CancelSubscription(ctx, req.(*CancelSubscriptionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BillingService_AddPaymentMethod_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddPaymentMethodRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BillingServiceServer).AddPaymentMethod(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BillingService_AddPaymentMethod_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BillingServiceServer).AddPaymentMethod(ctx, req.(*AddPaymentMethodRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BillingService_GetUserPaymentMethods_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserPaymentMethodsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BillingServiceServer).GetUserPaymentMethods(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BillingService_GetUserPaymentMethods_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BillingServiceServer).GetUserPaymentMethods(ctx, req.(*GetUserPaymentMethodsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BillingService_DeletePaymentMethod_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeletePaymentMethodRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BillingServiceServer).DeletePaymentMethod(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BillingService_DeletePaymentMethod_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BillingServiceServer).DeletePaymentMethod(ctx, req.(*DeletePaymentMethodRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BillingService_GetUserInvoices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserInvoicesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BillingServiceServer).GetUserInvoices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BillingService_GetUserInvoices_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BillingServiceServer).GetUserInvoices(ctx, req.(*GetUserInvoicesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BillingService_GetInvoice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInvoiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BillingServiceServer).GetInvoice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BillingService_GetInvoice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BillingServiceServer).GetInvoice(ctx, req.(*GetInvoiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BillingService_TrackUsage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TrackUsageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BillingServiceServer).TrackUsage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BillingService_TrackUsage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BillingServiceServer).TrackUsage(ctx, req.(*TrackUsageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BillingService_GetUserUsage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserUsageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BillingServiceServer).GetUserUsage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BillingService_GetUserUsage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BillingServiceServer).GetUserUsage(ctx, req.(*GetUserUsageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BillingService_ProcessWebhook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProcessWebhookRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BillingServiceServer).ProcessWebhook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BillingService_ProcessWebhook_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BillingServiceServer).ProcessWebhook(ctx, req.(*ProcessWebhookRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BillingService_GetBillingAnalytics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBillingAnalyticsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BillingServiceServer).GetBillingAnalytics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BillingService_GetBillingAnalytics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BillingServiceServer).GetBillingAnalytics(ctx, req.(*GetBillingAnalyticsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BillingService_ListAllSubscriptions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAllSubscriptionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BillingServiceServer).ListAllSubscriptions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BillingService_ListAllSubscriptions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BillingServiceServer).ListAllSubscriptions(ctx, req.(*ListAllSubscriptionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BillingService_ServiceDesc is the grpc.ServiceDesc for BillingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BillingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "billing.BillingService",
	HandlerType: (*BillingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPlans",
			Handler:    _BillingService_GetPlans_Handler,
		},
		{
			MethodName: "GetPlan",
			Handler:    _BillingService_GetPlan_Handler,
		},
		{
			MethodName: "GetEffectiveTier",
			Handler:    _BillingService_GetEffectiveTier_Handler,
		},
		{
			MethodName: "ListAllTiers",
			Handler:    _BillingService_ListAllTiers_Handler,
		},
		{
			MethodName: "CreateTier",
			Handler:    _BillingService_CreateTier_Handler,
		},
		{
			MethodName: "UpdateTier",
			Handler:    _BillingService_UpdateTier_Handler,
		},
		{
			MethodName: "DeleteTier",
			Handler:    _BillingService_DeleteTier_Handler,
		},
		{
			MethodName: "ReorderTiers",
			Handler:    _BillingService_ReorderTiers_Handler,
		},
		{
			MethodName: "ListGateways",
			Handler:    _BillingService_ListGateways_Handler,
		},
		{
			MethodName: "CreateSubscription",
			Handler:    _BillingService_CreateSubscription_Handler,
		},
		{
			MethodName: "GetUserSubscription",
			Handler:    _BillingService_GetUserSubscription_Handler,
		},
		{
			MethodName: "UpdateSubscription",
			Handler:    _BillingService_UpdateSubscription_Handler,
		},
		{
			MethodName: "CancelSubscription",
			Handler:    _BillingService_CancelSubscription_Handler,
		},
		{
			MethodName: "AddPaymentMethod",
			Handler:    _BillingService_AddPaymentMethod_Handler,
		},
		{
			MethodName: "GetUserPaymentMethods",
			Handler:    _BillingService_GetUserPaymentMethods_Handler,
		},
		{
			MethodName: "DeletePaymentMethod",
			Handler:    _BillingService_DeletePaymentMethod_Handler,
		},
		{
			MethodName: "GetUserInvoices",
			Handler:    _BillingService_GetUserInvoices_Handler,
		},
		{
			MethodName: "GetInvoice",
			Handler:    _BillingService_GetInvoice_Handler,
		},
		{
			MethodName: "TrackUsage",
			Handler:    _BillingService_TrackUsage_Handler,
		},
		{
			MethodName: "GetUserUsage",
			Handler:    _BillingService_GetUserUsage_Handler,
		},
		{
			MethodName: "ProcessWebhook",
			Handler:    _BillingService_ProcessWebhook_Handler,
		},
		{
			MethodName: "GetBillingAnalytics",
			Handler:    _BillingService_GetBillingAnalytics_Handler,
		},
		{
			MethodName: "ListAllSubscriptions",
			Handler:    _BillingService_ListAllSubscriptions_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "billing/billing.proto",
}
