// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: aisettings/aisettings.proto

package aisettings

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	common "inkwell/server/pkg/grpc/common"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ProviderSetting is one user's configured BYO AI provider. API keys are
// stored encrypted at rest (AES-256-GCM) and never appear on this message
// — callers get plaintext only via GetForDispatch, which is restricted to
// the gateway's internal network.
type ProviderSetting struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Kind          string                 `protobuf:"bytes,3,opt,name=kind,proto3" json:"kind,omitempty"` // openai | anthropic | gemini | openai_compatible
	Label         string                 `protobuf:"bytes,4,opt,name=label,proto3" json:"label,omitempty"`
	Enabled       bool                   `protobuf:"varint,5,opt,name=enabled,proto3" json:"enabled,omitempty"`
	BaseUrl       string                 `protobuf:"bytes,6,opt,name=base_url,json=baseUrl,proto3" json:"base_url,omitempty"` // optional; only meaningful for openai_compatible
	DefaultModel  string                 `protobuf:"bytes,7,opt,name=default_model,json=defaultModel,proto3" json:"default_model,omitempty"`
	HasKey        bool                   `protobuf:"varint,8,opt,name=has_key,json=hasKey,proto3" json:"has_key,omitempty"`
	KeyVersion    int32                  `protobuf:"varint,9,opt,name=key_version,json=keyVersion,proto3" json:"key_version,omitempty"`
	CreatedAt     *common.Timestamp      `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *common.Timestamp      `protobuf:"bytes,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProviderSetting) Reset() {
	*x = ProviderSetting{}
	mi := &file_aisettings_aisettings_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProviderSetting) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProviderSetting) ProtoMessage() {}

func (x *ProviderSetting) ProtoReflect() protoreflect.Message {
	mi := &file_aisettings_aisettings_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProviderSetting.ProtoReflect.Descriptor instead.
func (*ProviderSetting) Descriptor() ([]byte, []int) {
	return file_aisettings_aisettings_proto_rawDescGZIP(), []int{0}
}

func (x *ProviderSetting) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ProviderSetting) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ProviderSetting) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *ProviderSetting) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *ProviderSetting) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *ProviderSetting) GetBaseUrl() string {
	if x != nil {
		return x.BaseUrl
	}
	return ""
}

func (x *ProviderSetting) GetDefaultModel() string {
	if x != nil {
		return x.DefaultModel
	}
	return ""
}

func (x *ProviderSetting) GetHasKey() bool {
	if x != nil {
		return x.HasKey
	}
	return false
}

func (x *ProviderSetting) GetKeyVersion() int32 {
	if x != nil {
		return x.KeyVersion
	}
	return 0
}

func (x *ProviderSetting) GetCreatedAt() *common.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ProviderSetting) GetUpdatedAt() *common.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type ListProviderSettingsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProviderSettingsRequest) Reset() {
	*x = ListProviderSettingsRequest{}
	mi := &file_aisettings_aisettings_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProviderSettingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProviderSettingsRequest) ProtoMessage() {}

func (x *ListProviderSettingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aisettings_aisettings_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProviderSettingsRequest.ProtoReflect.Descriptor instead.
func (*ListProviderSettingsRequest) Descriptor() ([]byte, []int) {
	return file_aisettings_aisettings_proto_rawDescGZIP(), []int{1}
}

func (x *ListProviderSettingsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type ListProviderSettingsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Settings      []*ProviderSetting     `protobuf:"bytes,1,rep,name=settings,proto3" json:"settings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProviderSettingsResponse) Reset() {
	*x = ListProviderSettingsResponse{}
	mi := &file_aisettings_aisettings_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProviderSettingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProviderSettingsResponse) ProtoMessage() {}

func (x *ListProviderSettingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aisettings_aisettings_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProviderSettingsResponse.ProtoReflect.Descriptor instead.
func (*ListProviderSettingsResponse) Descriptor() ([]byte, []int) {
	return file_aisettings_aisettings_proto_rawDescGZIP(), []int{2}
}

func (x *ListProviderSettingsResponse) GetSettings() []*ProviderSetting {
	if x != nil {
		return x.Settings
	}
	return nil
}

type CreateProviderSettingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Kind          string                 `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	Label         string                 `protobuf:"bytes,3,opt,name=label,proto3" json:"label,omitempty"`
	Enabled       bool                   `protobuf:"varint,4,opt,name=enabled,proto3" json:"enabled,omitempty"`
	BaseUrl       string                 `protobuf:"bytes,5,opt,name=base_url,json=baseUrl,proto3" json:"base_url,omitempty"`
	DefaultModel  string                 `protobuf:"bytes,6,opt,name=default_model,json=defaultModel,proto3" json:"default_model,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProviderSettingRequest) Reset() {
	*x = CreateProviderSettingRequest{}
	mi := &file_aisettings_aisettings_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProviderSettingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProviderSettingRequest) ProtoMessage() {}

func (x *CreateProviderSettingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aisettings_aisettings_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProviderSettingRequest.ProtoReflect.Descriptor instead.
func (*CreateProviderSettingRequest) Descriptor() ([]byte, []int) {
	return file_aisettings_aisettings_proto_rawDescGZIP(), []int{3}
}

func (x *CreateProviderSettingRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateProviderSettingRequest) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *CreateProviderSettingRequest) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *CreateProviderSettingRequest) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *CreateProviderSettingRequest) GetBaseUrl() string {
	if x != nil {
		return x.BaseUrl
	}
	return ""
}

func (x *CreateProviderSettingRequest) GetDefaultModel() string {
	if x != nil {
		return x.DefaultModel
	}
	return ""
}

type CreateProviderSettingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Setting       *ProviderSetting       `protobuf:"bytes,1,opt,name=setting,proto3" json:"setting,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProviderSettingResponse) Reset() {
	*x = CreateProviderSettingResponse{}
	mi := &file_aisettings_aisettings_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProviderSettingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProviderSettingResponse) ProtoMessage() {}

func (x *CreateProviderSettingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aisettings_aisettings_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProviderSettingResponse.ProtoReflect.Descriptor instead.
func (*CreateProviderSettingResponse) Descriptor() ([]byte, []int) {
	return file_aisettings_aisettings_proto_rawDescGZIP(), []int{4}
}

func (x *CreateProviderSettingResponse) GetSetting() *ProviderSetting {
	if x != nil {
		return x.Setting
	}
	return nil
}

type UpdateProviderSettingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Kind          string                 `protobuf:"bytes,3,opt,name=kind,proto3" json:"kind,omitempty"`
	Label         string                 `protobuf:"bytes,4,opt,name=label,proto3" json:"label,omitempty"`
	Enabled       bool                   `protobuf:"varint,5,opt,name=enabled,proto3" json:"enabled,omitempty"`
	BaseUrl       string                 `protobuf:"bytes,6,opt,name=base_url,json=baseUrl,proto3" json:"base_url,omitempty"`
	DefaultModel  string                 `protobuf:"bytes,7,opt,name=default_model,json=defaultModel,proto3" json:"default_model,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProviderSettingRequest) Reset() {
	*x = UpdateProviderSettingRequest{}
	mi := &file_aisettings_aisettings_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProviderSettingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProviderSettingRequest) ProtoMessage() {}

func (x *UpdateProviderSettingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aisettings_aisettings_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProviderSettingRequest.ProtoReflect.Descriptor instead.
func (*UpdateProviderSettingRequest) Descriptor() ([]byte, []int) {
	return file_aisettings_aisettings_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateProviderSettingRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdateProviderSettingRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateProviderSettingRequest) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *UpdateProviderSettingRequest) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *UpdateProviderSettingRequest) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *UpdateProviderSettingRequest) GetBaseUrl() string {
	if x != nil {
		return x.BaseUrl
	}
	return ""
}

func (x *UpdateProviderSettingRequest) GetDefaultModel() string {
	if x != nil {
		return x.DefaultModel
	}
	return ""
}

type UpdateProviderSettingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Setting       *ProviderSetting       `protobuf:"bytes,1,opt,name=setting,proto3" json:"setting,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProviderSettingResponse) Reset() {
	*x = UpdateProviderSettingResponse{}
	mi := &file_aisettings_aisettings_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProviderSettingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProviderSettingResponse) ProtoMessage() {}

func (x *UpdateProviderSettingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aisettings_aisettings_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProviderSettingResponse.ProtoReflect.Descriptor instead.
func (*UpdateProviderSettingResponse) Descriptor() ([]byte, []int) {
	return file_aisettings_aisettings_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateProviderSettingResponse) GetSetting() *ProviderSetting {
	if x != nil {
		return x.Setting
	}
	return nil
}

type DeleteProviderSettingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteProviderSettingRequest) Reset() {
	*x = DeleteProviderSettingRequest{}
	mi := &file_aisettings_aisettings_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteProviderSettingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProviderSettingRequest) ProtoMessage() {}

func (x *DeleteProviderSettingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aisettings_aisettings_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteProviderSettingRequest.ProtoReflect.Descriptor instead.
func (*DeleteProviderSettingRequest) Descriptor() ([]byte, []int) {
	return file_aisettings_aisettings_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteProviderSettingRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *DeleteProviderSettingRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteProviderSettingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteProviderSettingResponse) Reset() {
	*x = DeleteProviderSettingResponse{}
	mi := &file_aisettings_aisettings_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteProviderSettingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProviderSettingResponse) ProtoMessage() {}

func (x *DeleteProviderSettingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aisettings_aisettings_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteProviderSettingResponse.ProtoReflect.Descriptor instead.
func (*DeleteProviderSettingResponse) Descriptor() ([]byte, []int) {
	return file_aisettings_aisettings_proto_rawDescGZIP(), []int{8}
}

type SetProviderKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	ApiKey        string                 `protobuf:"bytes,3,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetProviderKeyRequest) Reset() {
	*x = SetProviderKeyRequest{}
	mi := &file_aisettings_aisettings_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetProviderKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetProviderKeyRequest) ProtoMessage() {}

func (x *SetProviderKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aisettings_aisettings_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetProviderKeyRequest.ProtoReflect.Descriptor instead.
func (*SetProviderKeyRequest) Descriptor() ([]byte, []int) {
	return file_aisettings_aisettings_proto_rawDescGZIP(), []int{9}
}

func (x *SetProviderKeyRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SetProviderKeyRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SetProviderKeyRequest) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

type SetProviderKeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetProviderKeyResponse) Reset() {
	*x = SetProviderKeyResponse{}
	mi := &file_aisettings_aisettings_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetProviderKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetProviderKeyResponse) ProtoMessage() {}

func (x *SetProviderKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aisettings_aisettings_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetProviderKeyResponse.ProtoReflect.Descriptor instead.
func (*SetProviderKeyResponse) Descriptor() ([]byte, []int) {
	return file_aisettings_aisettings_proto_rawDescGZIP(), []int{10}
}

type ClearProviderKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClearProviderKeyRequest) Reset() {
	*x = ClearProviderKeyRequest{}
	mi := &file_aisettings_aisettings_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClearProviderKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearProviderKeyRequest) ProtoMessage() {}

func (x *ClearProviderKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aisettings_aisettings_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearProviderKeyRequest.ProtoReflect.Descriptor instead.
func (*ClearProviderKeyRequest) Descriptor() ([]byte, []int) {
	return file_aisettings_aisettings_proto_rawDescGZIP(), []int{11}
}

func (x *ClearProviderKeyRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ClearProviderKeyRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ClearProviderKeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClearProviderKeyResponse) Reset() {
	*x = ClearProviderKeyResponse{}
	mi := &file_aisettings_aisettings_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClearProviderKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearProviderKeyResponse) ProtoMessage() {}

func (x *ClearProviderKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aisettings_aisettings_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearProviderKeyResponse.ProtoReflect.Descriptor instead.
func (*ClearProviderKeyResponse) Descriptor() ([]byte, []int) {
	return file_aisettings_aisettings_proto_rawDescGZIP(), []int{12}
}

// GetForDispatch returns the plaintext key alongside the row. Intended
// for the gateway's chat path only — do not expose through any
// user-facing endpoint.
type GetForDispatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetForDispatchRequest) Reset() {
	*x = GetForDispatchRequest{}
	mi := &file_aisettings_aisettings_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetForDispatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetForDispatchRequest) ProtoMessage() {}

func (x *GetForDispatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aisettings_aisettings_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetForDispatchRequest.ProtoReflect.Descriptor instead.
func (*GetForDispatchRequest) Descriptor() ([]byte, []int) {
	return file_aisettings_aisettings_proto_rawDescGZIP(), []int{13}
}

func (x *GetForDispatchRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetForDispatchRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetForDispatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Setting       *ProviderSetting       `protobuf:"bytes,1,opt,name=setting,proto3" json:"setting,omitempty"`
	ApiKey        string                 `protobuf:"bytes,2,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"` // may be empty for keyless openai_compatible rows
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetForDispatchResponse) Reset() {
	*x = GetForDispatchResponse{}
	mi := &file_aisettings_aisettings_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetForDispatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetForDispatchResponse) ProtoMessage() {}

func (x *GetForDispatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aisettings_aisettings_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetForDispatchResponse.ProtoReflect.Descriptor instead.
func (*GetForDispatchResponse) Descriptor() ([]byte, []int) {
	return file_aisettings_aisettings_proto_rawDescGZIP(), []int{14}
}

func (x *GetForDispatchResponse) GetSetting() *ProviderSetting {
	if x != nil {
		return x.Setting
	}
	return nil
}

func (x *GetForDispatchResponse) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

var File_aisettings_aisettings_proto protoreflect.FileDescriptor

const file_aisettings_aisettings_proto_rawDesc = "" +
	"\n" +
	"\x1baisettings/aisettings.proto\x12\n" +
	"aisettings\x1a\x12common/types.proto\"\xdc\x02\n" +
	"\x0fProviderSetting\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x12\n" +
	"\x04kind\x18\x03 \x01(\tR\x04kind\x12\x14\n" +
	"\x05label\x18\x04 \x01(\tR\x05label\x12\x18\n" +
	"\aenabled\x18\x05 \x01(\bR\aenabled\x12\x19\n" +
	"\bbase_url\x18\x06 \x01(\tR\abaseUrl\x12#\n" +
	"\rdefault_model\x18\a \x01(\tR\fdefaultModel\x12\x17\n" +
	"\ahas_key\x18\b \x01(\bR\x06hasKey\x12\x1f\n" +
	"\vkey_version\x18\t \x01(\x05R\n" +
	"keyVersion\x120\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\v2\x11.common.TimestampR\tcreatedAt\x120\n" +
	"\n" +
	"updated_at\x18\v \x01(\v2\x11.common.TimestampR\tupdatedAt\"6\n" +
	"\x1bListProviderSettingsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"W\n" +
	"\x1cListProviderSettingsResponse\x127\n" +
	"\bsettings\x18\x01 \x03(\v2\x1b.aisettings.ProviderSettingR\bsettings\"\xbb\x01\n" +
	"\x1cCreateProviderSettingRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\x12\x14\n" +
	"\x05label\x18\x03 \x01(\tR\x05label\x12\x18\n" +
	"\aenabled\x18\x04 \x01(\bR\aenabled\x12\x19\n" +
	"\bbase_url\x18\x05 \x01(\tR\abaseUrl\x12#\n" +
	"\rdefault_model\x18\x06 \x01(\tR\fdefaultModel\"V\n" +
	"\x1dCreateProviderSettingResponse\x125\n" +
	"\asetting\x18\x01 \x01(\v2\x1b.aisettings.ProviderSettingR\asetting\"\xcb\x01\n" +
	"\x1cUpdateProviderSettingRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12\x12\n" +
	"\x04kind\x18\x03 \x01(\tR\x04kind\x12\x14\n" +
	"\x05label\x18\x04 \x01(\tR\x05label\x12\x18\n" +
	"\aenabled\x18\x05 \x01(\bR\aenabled\x12\x19\n" +
	"\bbase_url\x18\x06 \x01(\tR\abaseUrl\x12#\n" +
	"\rdefault_model\x18\a \x01(\tR\fdefaultModel\"V\n" +
	"\x1dUpdateProviderSettingResponse\x125\n" +
	"\asetting\x18\x01 \x01(\v2\x1b.aisettings.ProviderSettingR\asetting\"G\n" +
	"\x1cDeleteProviderSettingRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\"\x1f\n" +
	"\x1dDeleteProviderSettingResponse\"Y\n" +
	"\x15SetProviderKeyRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12\x17\n" +
	"\aapi_key\x18\x03 \x01(\tR\x06apiKey\"\x18\n" +
	"\x16SetProviderKeyResponse\"B\n" +
	"\x17ClearProviderKeyRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\"\x1a\n" +
	"\x18ClearProviderKeyResponse\"@\n" +
	"\x15GetForDispatchRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\"h\n" +
	"\x16GetForDispatchResponse\x125\n" +
	"\asetting\x18\x01 \x01(\v2\x1b.aisettings.ProviderSettingR\asetting\x12\x17\n" +
	"\aapi_key\x18\x02 \x01(\tR\x06apiKey2\xd9\x05\n" +
	"\x11AISettingsService\x12i\n" +
	"\x14ListProviderSettings\x12'.aisettings.ListProviderSettingsRequest\x1a(.aisettings.ListProviderSettingsResponse\x12l\n" +
	"\x15CreateProviderSetting\x12(.aisettings.CreateProviderSettingRequest\x1a).aisettings.CreateProviderSettingResponse\x12l\n" +
	"\x15UpdateProviderSetting\x12(.aisettings.UpdateProviderSettingRequest\x1a).aisettings.UpdateProviderSettingResponse\x12l\n" +
	"\x15DeleteProviderSetting\x12(.aisettings.DeleteProviderSettingRequest\x1a).aisettings.DeleteProviderSettingResponse\x12W\n" +
	"\x0eSetProviderKey\x12!.aisettings.SetProviderKeyRequest\x1a\".aisettings.SetProviderKeyResponse\x12]\n" +
	"\x10ClearProviderKey\x12#.aisettings.ClearProviderKeyRequest\x1a$.aisettings.ClearProviderKeyResponse\x12W\n" +
	"\x0eGetForDispatch\x12!.aisettings.GetForDispatchRequest\x1a\".aisettings.GetForDispatchResponseB$Z\"inkwell/server/pkg/grpc/aisettingsb\x06proto3"

var (
	file_aisettings_aisettings_proto_rawDescOnce sync.Once
	file_aisettings_aisettings_proto_rawDescData []byte
)

func file_aisettings_aisettings_proto_rawDescGZIP() []byte {
	file_aisettings_aisettings_proto_rawDescOnce.Do(func() {
		file_aisettings_aisettings_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_aisettings_aisettings_proto_rawDesc), len(file_aisettings_aisettings_proto_rawDesc)))
	})
	return file_aisettings_aisettings_proto_rawDescData
}

var file_aisettings_aisettings_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_aisettings_aisettings_proto_goTypes = []any{
	(*ProviderSetting)(nil),               // 0: aisettings.ProviderSetting
	(*ListProviderSettingsRequest)(nil),   // 1: aisettings.ListProviderSettingsRequest
	(*ListProviderSettingsResponse)(nil),  // 2: aisettings.ListProviderSettingsResponse
	(*CreateProviderSettingRequest)(nil),  // 3: aisettings.CreateProviderSettingRequest
	(*CreateProviderSettingResponse)(nil), // 4: aisettings.CreateProviderSettingResponse
	(*UpdateProviderSettingRequest)(nil),  // 5: aisettings.UpdateProviderSettingRequest
	(*UpdateProviderSettingResponse)(nil), // 6: aisettings.UpdateProviderSettingResponse
	(*DeleteProviderSettingRequest)(nil),  // 7: aisettings.DeleteProviderSettingRequest
	(*DeleteProviderSettingResponse)(nil), // 8: aisettings.DeleteProviderSettingResponse
	(*SetProviderKeyRequest)(nil),         // 9: aisettings.SetProviderKeyRequest
	(*SetProviderKeyResponse)(nil),        // 10: aisettings.SetProviderKeyResponse
	(*ClearProviderKeyRequest)(nil),       // 11: aisettings.ClearProviderKeyRequest
	(*ClearProviderKeyResponse)(nil),      // 12: aisettings.ClearProviderKeyResponse
	(*GetForDispatchRequest)(nil),         // 13: aisettings.GetForDispatchRequest
	(*GetForDispatchResponse)(nil),        // 14: aisettings.GetForDispatchResponse
	(*common.Timestamp)(nil),              // 15: common.Timestamp
}
var file_aisettings_aisettings_proto_depIdxs = []int32{
	15, // 0: aisettings.ProviderSetting.created_at:type_name -> common.Timestamp
	15, // 1: aisettings.ProviderSetting.updated_at:type_name -> common.Timestamp
	0,  // 2: aisettings.ListProviderSettingsResponse.settings:type_name -> aisettings.ProviderSetting
	0,  // 3: aisettings.CreateProviderSettingResponse.setting:type_name -> aisettings.ProviderSetting
	0,  // 4: aisettings.UpdateProviderSettingResponse.setting:type_name -> aisettings.ProviderSetting
	0,  // 5: aisettings.GetForDispatchResponse.setting:type_name -> aisettings.ProviderSetting
	1,  // 6: aisettings.AISettingsService.ListProviderSettings:input_type -> aisettings.ListProviderSettingsRequest
	3,  // 7: aisettings.AISettingsService.CreateProviderSetting:input_type -> aisettings.CreateProviderSettingRequest
	5,  // 8: aisettings.AISettingsService.UpdateProviderSetting:input_type -> aisettings.UpdateProviderSettingRequest
	7,  // 9: aisettings.AISettingsService.DeleteProviderSetting:input_type -> aisettings.DeleteProviderSettingRequest
	9,  // 10: aisettings.AISettingsService.SetProviderKey:input_type -> aisettings.SetProviderKeyRequest
	11, // 11: aisettings.AISettingsService.ClearProviderKey:input_type -> aisettings.ClearProviderKeyRequest
	13, // 12: aisettings.AISettingsService.GetForDispatch:input_type -> aisettings.GetForDispatchRequest
	2,  // 13: aisettings.AISettingsService.ListProviderSettings:output_type -> aisettings.ListProviderSettingsResponse
	4,  // 14: aisettings.AISettingsService.CreateProviderSetting:output_type -> aisettings.CreateProviderSettingResponse
	6,  // 15: aisettings.AISettingsService.UpdateProviderSetting:output_type -> aisettings.UpdateProviderSettingResponse
	8,  // 16: aisettings.AISettingsService.DeleteProviderSetting:output_type -> aisettings.DeleteProviderSettingResponse
	10, // 17: aisettings.AISettingsService.SetProviderKey:output_type -> aisettings.SetProviderKeyResponse
	12, // 18: aisettings.AISettingsService.ClearProviderKey:output_type -> aisettings.ClearProviderKeyResponse
	14, // 19: aisettings.AISettingsService.GetForDispatch:output_type -> aisettings.GetForDispatchResponse
	13, // [13:20] is the sub-list for method output_type
	6,  // [6:13] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_aisettings_aisettings_proto_init() }
func file_aisettings_aisettings_proto_init() {
	if File_aisettings_aisettings_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_aisettings_aisettings_proto_rawDesc), len(file_aisettings_aisettings_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_aisettings_aisettings_proto_goTypes,
		DependencyIndexes: file_aisettings_aisettings_proto_depIdxs,
		MessageInfos:      file_aisettings_aisettings_proto_msgTypes,
	}.Build()
	File_aisettings_aisettings_proto = out.File
	file_aisettings_aisettings_proto_goTypes = nil
	file_aisettings_aisettings_proto_depIdxs = nil
}
