// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v4.25.1
// source: scripts/scripts.proto

package scripts

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ScriptsService_CreateProject_FullMethodName        = "/scripts.ScriptsService/CreateProject"
	ScriptsService_GetProject_FullMethodName           = "/scripts.ScriptsService/GetProject"
	ScriptsService_UpdateProject_FullMethodName        = "/scripts.ScriptsService/UpdateProject"
	ScriptsService_ToggleProjectStar_FullMethodName    = "/scripts.ScriptsService/ToggleProjectStar"
	ScriptsService_DeleteProject_FullMethodName        = "/scripts.ScriptsService/DeleteProject"
	ScriptsService_GetUserProjects_FullMethodName      = "/scripts.ScriptsService/GetUserProjects"
	ScriptsService_GetOrgProjects_FullMethodName       = "/scripts.ScriptsService/GetOrgProjects"
	ScriptsService_CreateOutlineUnit_FullMethodName    = "/scripts.ScriptsService/CreateOutlineUnit"
	ScriptsService_GetProjectOutline_FullMethodName    = "/scripts.ScriptsService/GetProjectOutline"
	ScriptsService_UpdateOutlineUnit_FullMethodName    = "/scripts.ScriptsService/UpdateOutlineUnit"
	ScriptsService_DeleteOutlineUnit_FullMethodName    = "/scripts.ScriptsService/DeleteOutlineUnit"
	ScriptsService_CreateScene_FullMethodName          = "/scripts.ScriptsService/CreateScene"
	ScriptsService_GetProjectScenes_FullMethodName     = "/scripts.ScriptsService/GetProjectScenes"
	ScriptsService_UpdateScene_FullMethodName          = "/scripts.ScriptsService/UpdateScene"
	ScriptsService_DeleteScene_FullMethodName          = "/scripts.ScriptsService/DeleteScene"
	ScriptsService_CreateCharacter_FullMethodName      = "/scripts.ScriptsService/CreateCharacter"
	ScriptsService_GetProjectCharacters_FullMethodName = "/scripts.ScriptsService/GetProjectCharacters"
	ScriptsService_UpdateCharacter_FullMethodName      = "/scripts.ScriptsService/UpdateCharacter"
	ScriptsService_CreateLocation_FullMethodName       = "/scripts.ScriptsService/CreateLocation"
	ScriptsService_GetProjectLocations_FullMethodName  = "/scripts.ScriptsService/GetProjectLocations"
	ScriptsService_CreateElement_FullMethodName        = "/scripts.ScriptsService/CreateElement"
	ScriptsService_UpdateElement_FullMethodName        = "/scripts.ScriptsService/UpdateElement"
	ScriptsService_GetSceneElements_FullMethodName     = "/scripts.ScriptsService/GetSceneElements"
	ScriptsService_DeleteScriptElement_FullMethodName  = "/scripts.ScriptsService/DeleteScriptElement"
	ScriptsService_BatchCreateElements_FullMethodName  = "/scripts.ScriptsService/BatchCreateElements"
	ScriptsService_CreateBeat_FullMethodName           = "/scripts.ScriptsService/CreateBeat"
	ScriptsService_GetBeat_FullMethodName              = "/scripts.ScriptsService/GetBeat"
	ScriptsService_GetProjectBeatBoard_FullMethodName  = "/scripts.ScriptsService/GetProjectBeatBoard"
	ScriptsService_UpdateBeat_FullMethodName           = "/scripts.ScriptsService/UpdateBeat"
	ScriptsService_DeleteBeat_FullMethodName           = "/scripts.ScriptsService/DeleteBeat"
	ScriptsService_CreateConnection_FullMethodName     = "/scripts.ScriptsService/CreateConnection"
	ScriptsService_DeleteConnection_FullMethodName     = "/scripts.ScriptsService/DeleteConnection"
	ScriptsService_CreateLane_FullMethodName           = "/scripts.ScriptsService/CreateLane"
	ScriptsService_GetProjectLanes_FullMethodName      = "/scripts.ScriptsService/GetProjectLanes"
	ScriptsService_UpdateLane_FullMethodName           = "/scripts.ScriptsService/UpdateLane"
	ScriptsService_UpdateLaneOrder_FullMethodName      = "/scripts.ScriptsService/UpdateLaneOrder"
	ScriptsService_DeleteLane_FullMethodName           = "/scripts.ScriptsService/DeleteLane"
	ScriptsService_CreateOutlineItem_FullMethodName    = "/scripts.ScriptsService/CreateOutlineItem"
	ScriptsService_UpdateOutlineItem_FullMethodName    = "/scripts.ScriptsService/UpdateOutlineItem"
	ScriptsService_DeleteOutlineItem_FullMethodName    = "/scripts.ScriptsService/DeleteOutlineItem"
	ScriptsService_GetResourceProject_FullMethodName   = "/scripts.ScriptsService/GetResourceProject"
	ScriptsService_SyncProject_FullMethodName          = "/scripts.ScriptsService/SyncProject"
	ScriptsService_SyncVault_FullMethodName            = "/scripts.ScriptsService/SyncVault"
)

// ScriptsServiceClient is the client API for ScriptsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ScriptsServiceClient interface {
	// Project management (Project now represents the screenplay)
	CreateProject(ctx context.Context, in *CreateProjectRequest, opts ...grpc.CallOption) (*CreateProjectResponse, error)
	GetProject(ctx context.Context, in *GetProjectRequest, opts ...grpc.CallOption) (*GetProjectResponse, error)
	UpdateProject(ctx context.Context, in *UpdateProjectRequest, opts ...grpc.CallOption) (*UpdateProjectResponse, error)
	ToggleProjectStar(ctx context.Context, in *ToggleProjectStarRequest, opts ...grpc.CallOption) (*ToggleProjectStarResponse, error)
	DeleteProject(ctx context.Context, in *DeleteProjectRequest, opts ...grpc.CallOption) (*DeleteProjectResponse, error)
	GetUserProjects(ctx context.Context, in *GetUserProjectsRequest, opts ...grpc.CallOption) (*GetUserProjectsResponse, error)
	GetOrgProjects(ctx context.Context, in *GetOrgProjectsRequest, opts ...grpc.CallOption) (*GetOrgProjectsResponse, error)
	// Outline unit management (acts, sequences, beats, sub-beats)
	CreateOutlineUnit(ctx context.Context, in *CreateOutlineUnitRequest, opts ...grpc.CallOption) (*CreateOutlineUnitResponse, error)
	GetProjectOutline(ctx context.Context, in *GetProjectOutlineRequest, opts ...grpc.CallOption) (*GetProjectOutlineResponse, error)
	UpdateOutlineUnit(ctx context.Context, in *UpdateOutlineUnitRequest, opts ...grpc.CallOption) (*UpdateOutlineUnitResponse, error)
	DeleteOutlineUnit(ctx context.Context, in *DeleteOutlineUnitRequest, opts ...grpc.CallOption) (*DeleteOutlineUnitResponse, error)
	// Scene management
	CreateScene(ctx context.Context, in *CreateSceneRequest, opts ...grpc.CallOption) (*CreateSceneResponse, error)
	GetProjectScenes(ctx context.Context, in *GetProjectScenesRequest, opts ...grpc.CallOption) (*GetProjectScenesResponse, error)
	UpdateScene(ctx context.Context, in *UpdateSceneRequest, opts ...grpc.CallOption) (*UpdateSceneResponse, error)
	DeleteScene(ctx context.Context, in *DeleteSceneRequest, opts ...grpc.CallOption) (*DeleteSceneResponse, error)
	// Character management
	CreateCharacter(ctx context.Context, in *CreateCharacterRequest, opts ...grpc.CallOption) (*CreateCharacterResponse, error)
	GetProjectCharacters(ctx context.Context, in *GetProjectCharactersRequest, opts ...grpc.CallOption) (*GetProjectCharactersResponse, error)
	UpdateCharacter(ctx context.Context, in *UpdateCharacterRequest, opts ...grpc.CallOption) (*UpdateCharacterResponse, error)
	// Location management
	CreateLocation(ctx context.Context, in *CreateLocationRequest, opts ...grpc.CallOption) (*CreateLocationResponse, error)
	GetProjectLocations(ctx context.Context, in *GetProjectLocationsRequest, opts ...grpc.CallOption) (*GetProjectLocationsResponse, error)
	// Element operations. CreateElement / UpdateElement / GetSceneElements back
	// the gateway's element CRUD; DeleteScriptElement deletes by id;
	// BatchCreateElements persists a scene's elements in one call (FDX import).
	CreateElement(ctx context.Context, in *CreateElementRequest, opts ...grpc.CallOption) (*CreateElementResponse, error)
	UpdateElement(ctx context.Context, in *UpdateElementRequest, opts ...grpc.CallOption) (*UpdateElementResponse, error)
	GetSceneElements(ctx context.Context, in *GetSceneElementsRequest, opts ...grpc.CallOption) (*GetSceneElementsResponse, error)
	DeleteScriptElement(ctx context.Context, in *DeleteScriptElementRequest, opts ...grpc.CallOption) (*DeleteScriptElementResponse, error)
	BatchCreateElements(ctx context.Context, in *BatchCreateElementsRequest, opts ...grpc.CallOption) (*BatchCreateElementsResponse, error)
	// Beat Board management
	CreateBeat(ctx context.Context, in *CreateBeatRequest, opts ...grpc.CallOption) (*CreateBeatResponse, error)
	GetBeat(ctx context.Context, in *GetBeatRequest, opts ...grpc.CallOption) (*GetBeatResponse, error)
	GetProjectBeatBoard(ctx context.Context, in *GetProjectBeatBoardRequest, opts ...grpc.CallOption) (*GetProjectBeatBoardResponse, error)
	UpdateBeat(ctx context.Context, in *UpdateBeatRequest, opts ...grpc.CallOption) (*UpdateBeatResponse, error)
	DeleteBeat(ctx context.Context, in *DeleteBeatRequest, opts ...grpc.CallOption) (*DeleteBeatResponse, error)
	CreateConnection(ctx context.Context, in *CreateConnectionRequest, opts ...grpc.CallOption) (*CreateConnectionResponse, error)
	DeleteConnection(ctx context.Context, in *DeleteConnectionRequest, opts ...grpc.CallOption) (*DeleteConnectionResponse, error)
	CreateLane(ctx context.Context, in *CreateLaneRequest, opts ...grpc.CallOption) (*CreateLaneResponse, error)
	GetProjectLanes(ctx context.Context, in *GetProjectLanesRequest, opts ...grpc.CallOption) (*GetProjectLanesResponse, error)
	UpdateLane(ctx context.Context, in *UpdateLaneRequest, opts ...grpc.CallOption) (*UpdateLaneResponse, error)
	UpdateLaneOrder(ctx context.Context, in *UpdateLaneOrderRequest, opts ...grpc.CallOption) (*UpdateLaneOrderResponse, error)
	DeleteLane(ctx context.Context, in *DeleteLaneRequest, opts ...grpc.CallOption) (*DeleteLaneResponse, error)
	CreateOutlineItem(ctx context.Context, in *CreateOutlineItemRequest, opts ...grpc.CallOption) (*CreateOutlineItemResponse, error)
	UpdateOutlineItem(ctx context.Context, in *UpdateOutlineItemRequest, opts ...grpc.CallOption) (*UpdateOutlineItemResponse, error)
	DeleteOutlineItem(ctx context.Context, in *DeleteOutlineItemRequest, opts ...grpc.CallOption) (*DeleteOutlineItemResponse, error)
	// GetResourceProject resolves which project owns a sub-resource (beat, lane,
	// connection, outline item, or element). The gateway calls it to authorize
	// mutations against the resource's real project. It is an internal lookup —
	// no ownership check — so the gateway must authorize the returned project.
	GetResourceProject(ctx context.Context, in *GetResourceProjectRequest, opts ...grpc.CallOption) (*GetResourceProjectResponse, error)
	// SyncProject reconciles one project bidirectionally: it applies the caller's
	// pushed changes (upsert-by-id, server-stamped updated_at, last-sync-wins) and
	// returns every row changed since the caller's cursor. See SYNC_DESIGN.md.
	SyncProject(ctx context.Context, in *SyncProjectRequest, opts ...grpc.CallOption) (*SyncProjectResponse, error)
	// SyncVault reconciles a vault project's files bidirectionally, keyed by path
	// (upsert-by-path, server-stamped updated_at, last-sync-wins). Paginated: when
	// the response sets has_more, call again with the returned cursor until it is
	// false. See SYNC_DESIGN.md ("vault file sync").
	SyncVault(ctx context.Context, in *SyncVaultRequest, opts ...grpc.CallOption) (*SyncVaultResponse, error)
}

type scriptsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewScriptsServiceClient(cc grpc.ClientConnInterface) ScriptsServiceClient {
	return &scriptsServiceClient{cc}
}

func (c *scriptsServiceClient) CreateProject(ctx context.Context, in *CreateProjectRequest, opts ...grpc.CallOption) (*CreateProjectResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateProjectResponse)
	err := c.cc.Invoke(ctx, ScriptsService_CreateProject_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scriptsServiceClient) GetProject(ctx context.Context, in *GetProjectRequest, opts ...grpc.CallOption) (*GetProjectResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetProjectResponse)
	err := c.cc.Invoke(ctx, ScriptsService_GetProject_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scriptsServiceClient) UpdateProject(ctx context.Context, in *UpdateProjectRequest, opts ...grpc.CallOption) (*UpdateProjectResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateProjectResponse)
	err := c.cc.Invoke(ctx, ScriptsService_UpdateProject_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scriptsServiceClient) ToggleProjectStar(ctx context.Context, in *ToggleProjectStarRequest, opts ...grpc.CallOption) (*ToggleProjectStarResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ToggleProjectStarResponse)
	err := c.cc.Invoke(ctx, ScriptsService_ToggleProjectStar_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scriptsServiceClient) DeleteProject(ctx context.Context, in *DeleteProjectRequest, opts ...grpc.CallOption) (*DeleteProjectResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteProjectResponse)
	err := c.cc.Invoke(ctx, ScriptsService_DeleteProject_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scriptsServiceClient) GetUserProjects(ctx context.Context, in *GetUserProjectsRequest, opts ...grpc.CallOption) (*GetUserProjectsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserProjectsResponse)
	err := c.cc.Invoke(ctx, ScriptsService_GetUserProjects_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scriptsServiceClient) GetOrgProjects(ctx context.Context, in *GetOrgProjectsRequest, opts ...grpc.CallOption) (*GetOrgProjectsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetOrgProjectsResponse)
	err := c.cc.Invoke(ctx, ScriptsService_GetOrgProjects_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scriptsServiceClient) CreateOutlineUnit(ctx context.Context, in *CreateOutlineUnitRequest, opts ...grpc.CallOption) (*CreateOutlineUnitResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateOutlineUnitResponse)
	err := c.cc.Invoke(ctx, ScriptsService_CreateOutlineUnit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scriptsServiceClient) GetProjectOutline(ctx context.Context, in *GetProjectOutlineRequest, opts ...grpc.CallOption) (*GetProjectOutlineResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetProjectOutlineResponse)
	err := c.cc.Invoke(ctx, ScriptsService_GetProjectOutline_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scriptsServiceClient) UpdateOutlineUnit(ctx context.Context, in *UpdateOutlineUnitRequest, opts ...grpc.CallOption) (*UpdateOutlineUnitResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateOutlineUnitResponse)
	err := c.cc.Invoke(ctx, ScriptsService_UpdateOutlineUnit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scriptsServiceClient) DeleteOutlineUnit(ctx context.Context, in *DeleteOutlineUnitRequest, opts ...grpc.CallOption) (*DeleteOutlineUnitResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteOutlineUnitResponse)
	err := c.cc.Invoke(ctx, ScriptsService_DeleteOutlineUnit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scriptsServiceClient) CreateScene(ctx context.Context, in *CreateSceneRequest, opts ...grpc.CallOption) (*CreateSceneResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateSceneResponse)
	err := c.cc.Invoke(ctx, ScriptsService_CreateScene_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scriptsServiceClient) GetProjectScenes(ctx context.Context, in *GetProjectScenesRequest, opts ...grpc.CallOption) (*GetProjectScenesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetProjectScenesResponse)
	err := c.cc.Invoke(ctx, ScriptsService_GetProjectScenes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scriptsServiceClient) UpdateScene(ctx context.Context, in *UpdateSceneRequest, opts ...grpc.CallOption) (*UpdateSceneResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateSceneResponse)
	err := c.cc.Invoke(ctx, ScriptsService_UpdateScene_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scriptsServiceClient) DeleteScene(ctx context.Context, in *DeleteSceneRequest, opts ...grpc.CallOption) (*DeleteSceneResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteSceneResponse)
	err := c.cc.Invoke(ctx, ScriptsService_DeleteScene_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scriptsServiceClient) CreateCharacter(ctx context.Context, in *CreateCharacterRequest, opts ...grpc.CallOption) (*CreateCharacterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateCharacterResponse)
	err := c.cc.Invoke(ctx, ScriptsService_CreateCharacter_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scriptsServiceClient) GetProjectCharacters(ctx context.Context, in *GetProjectCharactersRequest, opts ...grpc.CallOption) (*GetProjectCharactersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetProjectCharactersResponse)
	err := c.cc.Invoke(ctx, ScriptsService_GetProjectCharacters_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scriptsServiceClient) UpdateCharacter(ctx context.Context, in *UpdateCharacterRequest, opts ...grpc.CallOption) (*UpdateCharacterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateCharacterResponse)
	err := c.cc.Invoke(ctx, ScriptsService_UpdateCharacter_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scriptsServiceClient) CreateLocation(ctx context.Context, in *CreateLocationRequest, opts ...grpc.CallOption) (*CreateLocationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateLocationResponse)
	err := c.cc.Invoke(ctx, ScriptsService_CreateLocation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scriptsServiceClient) GetProjectLocations(ctx context.Context, in *GetProjectLocationsRequest, opts ...grpc.CallOption) (*GetProjectLocationsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetProjectLocationsResponse)
	err := c.cc.Invoke(ctx, ScriptsService_GetProjectLocations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scriptsServiceClient) CreateElement(ctx context.Context, in *CreateElementRequest, opts ...grpc.CallOption) (*CreateElementResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateElementResponse)
	err := c.cc.Invoke(ctx, ScriptsService_CreateElement_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scriptsServiceClient) UpdateElement(ctx context.Context, in *UpdateElementRequest, opts ...grpc.CallOption) (*UpdateElementResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateElementResponse)
	err := c.cc.Invoke(ctx, ScriptsService_UpdateElement_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scriptsServiceClient) GetSceneElements(ctx context.Context, in *GetSceneElementsRequest, opts ...grpc.CallOption) (*GetSceneElementsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSceneElementsResponse)
	err := c.cc.Invoke(ctx, ScriptsService_GetSceneElements_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scriptsServiceClient) DeleteScriptElement(ctx context.Context, in *DeleteScriptElementRequest, opts ...grpc.CallOption) (*DeleteScriptElementResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteScriptElementResponse)
	err := c.cc.Invoke(ctx, ScriptsService_DeleteScriptElement_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scriptsServiceClient) BatchCreateElements(ctx context.Context, in *BatchCreateElementsRequest, opts ...grpc.CallOption) (*BatchCreateElementsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchCreateElementsResponse)
	err := c.cc.Invoke(ctx, ScriptsService_BatchCreateElements_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scriptsServiceClient) CreateBeat(ctx context.Context, in *CreateBeatRequest, opts ...grpc.CallOption) (*CreateBeatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateBeatResponse)
	err := c.cc.Invoke(ctx, ScriptsService_CreateBeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scriptsServiceClient) GetBeat(ctx context.Context, in *GetBeatRequest, opts ...grpc.CallOption) (*GetBeatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBeatResponse)
	err := c.cc.Invoke(ctx, ScriptsService_GetBeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scriptsServiceClient) GetProjectBeatBoard(ctx context.Context, in *GetProjectBeatBoardRequest, opts ...grpc.CallOption) (*GetProjectBeatBoardResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetProjectBeatBoardResponse)
	err := c.cc.Invoke(ctx, ScriptsService_GetProjectBeatBoard_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scriptsServiceClient) UpdateBeat(ctx context.Context, in *UpdateBeatRequest, opts ...grpc.CallOption) (*UpdateBeatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateBeatResponse)
	err := c.cc.Invoke(ctx, ScriptsService_UpdateBeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scriptsServiceClient) DeleteBeat(ctx context.Context, in *DeleteBeatRequest, opts ...grpc.CallOption) (*DeleteBeatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteBeatResponse)
	err := c.cc.Invoke(ctx, ScriptsService_DeleteBeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scriptsServiceClient) CreateConnection(ctx context.Context, in *CreateConnectionRequest, opts ...grpc.CallOption) (*CreateConnectionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateConnectionResponse)
	err := c.cc.Invoke(ctx, ScriptsService_CreateConnection_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scriptsServiceClient) DeleteConnection(ctx context.Context, in *DeleteConnectionRequest, opts ...grpc.CallOption) (*DeleteConnectionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteConnectionResponse)
	err := c.cc.Invoke(ctx, ScriptsService_DeleteConnection_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scriptsServiceClient) CreateLane(ctx context.Context, in *CreateLaneRequest, opts ...grpc.CallOption) (*CreateLaneResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateLaneResponse)
	err := c.cc.Invoke(ctx, ScriptsService_CreateLane_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scriptsServiceClient) GetProjectLanes(ctx context.Context, in *GetProjectLanesRequest, opts ...grpc.CallOption) (*GetProjectLanesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetProjectLanesResponse)
	err := c.cc.Invoke(ctx, ScriptsService_GetProjectLanes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scriptsServiceClient) UpdateLane(ctx context.Context, in *UpdateLaneRequest, opts ...grpc.CallOption) (*UpdateLaneResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateLaneResponse)
	err := c.cc.Invoke(ctx, ScriptsService_UpdateLane_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scriptsServiceClient) UpdateLaneOrder(ctx context.Context, in *UpdateLaneOrderRequest, opts ...grpc.CallOption) (*UpdateLaneOrderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateLaneOrderResponse)
	err := c.cc.Invoke(ctx, ScriptsService_UpdateLaneOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scriptsServiceClient) DeleteLane(ctx context.Context, in *DeleteLaneRequest, opts ...grpc.CallOption) (*DeleteLaneResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteLaneResponse)
	err := c.cc.Invoke(ctx, ScriptsService_DeleteLane_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scriptsServiceClient) CreateOutlineItem(ctx context.Context, in *CreateOutlineItemRequest, opts ...grpc.CallOption) (*CreateOutlineItemResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateOutlineItemResponse)
	err := c.cc.Invoke(ctx, ScriptsService_CreateOutlineItem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scriptsServiceClient) UpdateOutlineItem(ctx context.Context, in *UpdateOutlineItemRequest, opts ...grpc.CallOption) (*UpdateOutlineItemResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateOutlineItemResponse)
	err := c.cc.Invoke(ctx, ScriptsService_UpdateOutlineItem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scriptsServiceClient) DeleteOutlineItem(ctx context.Context, in *DeleteOutlineItemRequest, opts ...grpc.CallOption) (*DeleteOutlineItemResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteOutlineItemResponse)
	err := c.cc.Invoke(ctx, ScriptsService_DeleteOutlineItem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scriptsServiceClient) GetResourceProject(ctx context.Context, in *GetResourceProjectRequest, opts ...grpc.CallOption) (*GetResourceProjectResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetResourceProjectResponse)
	err := c.cc.Invoke(ctx, ScriptsService_GetResourceProject_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scriptsServiceClient) SyncProject(ctx context.Context, in *SyncProjectRequest, opts ...grpc.CallOption) (*SyncProjectResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SyncProjectResponse)
	err := c.cc.Invoke(ctx, ScriptsService_SyncProject_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scriptsServiceClient) SyncVault(ctx context.Context, in *SyncVaultRequest, opts ...grpc.CallOption) (*SyncVaultResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SyncVaultResponse)
	err := c.cc.Invoke(ctx, ScriptsService_SyncVault_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ScriptsServiceServer is the server API for ScriptsService service.
// All implementations must embed UnimplementedScriptsServiceServer
// for forward compatibility.
type ScriptsServiceServer interface {
	// Project management (Project now represents the screenplay)
	CreateProject(context.Context, *CreateProjectRequest) (*CreateProjectResponse, error)
	GetProject(context.Context, *GetProjectRequest) (*GetProjectResponse, error)
	UpdateProject(context.Context, *UpdateProjectRequest) (*UpdateProjectResponse, error)
	ToggleProjectStar(context.Context, *ToggleProjectStarRequest) (*ToggleProjectStarResponse, error)
	DeleteProject(context.Context, *DeleteProjectRequest) (*DeleteProjectResponse, error)
	GetUserProjects(context.Context, *GetUserProjectsRequest) (*GetUserProjectsResponse, error)
	GetOrgProjects(context.Context, *GetOrgProjectsRequest) (*GetOrgProjectsResponse, error)
	// Outline unit management (acts, sequences, beats, sub-beats)
	CreateOutlineUnit(context.Context, *CreateOutlineUnitRequest) (*CreateOutlineUnitResponse, error)
	GetProjectOutline(context.Context, *GetProjectOutlineRequest) (*GetProjectOutlineResponse, error)
	UpdateOutlineUnit(context.Context, *UpdateOutlineUnitRequest) (*UpdateOutlineUnitResponse, error)
	DeleteOutlineUnit(context.Context, *DeleteOutlineUnitRequest) (*DeleteOutlineUnitResponse, error)
	// Scene management
	CreateScene(context.Context, *CreateSceneRequest) (*CreateSceneResponse, error)
	GetProjectScenes(context.Context, *GetProjectScenesRequest) (*GetProjectScenesResponse, error)
	UpdateScene(context.Context, *UpdateSceneRequest) (*UpdateSceneResponse, error)
	DeleteScene(context.Context, *DeleteSceneRequest) (*DeleteSceneResponse, error)
	// Character management
	CreateCharacter(context.Context, *CreateCharacterRequest) (*CreateCharacterResponse, error)
	GetProjectCharacters(context.Context, *GetProjectCharactersRequest) (*GetProjectCharactersResponse, error)
	UpdateCharacter(context.Context, *UpdateCharacterRequest) (*UpdateCharacterResponse, error)
	// Location management
	CreateLocation(context.Context, *CreateLocationRequest) (*CreateLocationResponse, error)
	GetProjectLocations(context.Context, *GetProjectLocationsRequest) (*GetProjectLocationsResponse, error)
	// Element operations. CreateElement / UpdateElement / GetSceneElements back
	// the gateway's element CRUD; DeleteScriptElement deletes by id;
	// BatchCreateElements persists a scene's elements in one call (FDX import).
	CreateElement(context.Context, *CreateElementRequest) (*CreateElementResponse, error)
	UpdateElement(context.Context, *UpdateElementRequest) (*UpdateElementResponse, error)
	GetSceneElements(context.Context, *GetSceneElementsRequest) (*GetSceneElementsResponse, error)
	DeleteScriptElement(context.Context, *DeleteScriptElementRequest) (*DeleteScriptElementResponse, error)
	BatchCreateElements(context.Context, *BatchCreateElementsRequest) (*BatchCreateElementsResponse, error)
	// Beat Board management
	CreateBeat(context.Context, *CreateBeatRequest) (*CreateBeatResponse, error)
	GetBeat(context.Context, *GetBeatRequest) (*GetBeatResponse, error)
	GetProjectBeatBoard(context.Context, *GetProjectBeatBoardRequest) (*GetProjectBeatBoardResponse, error)
	UpdateBeat(context.Context, *UpdateBeatRequest) (*UpdateBeatResponse, error)
	DeleteBeat(context.Context, *DeleteBeatRequest) (*DeleteBeatResponse, error)
	CreateConnection(context.Context, *CreateConnectionRequest) (*CreateConnectionResponse, error)
	DeleteConnection(context.Context, *DeleteConnectionRequest) (*DeleteConnectionResponse, error)
	CreateLane(context.Context, *CreateLaneRequest) (*CreateLaneResponse, error)
	GetProjectLanes(context.Context, *GetProjectLanesRequest) (*GetProjectLanesResponse, error)
	UpdateLane(context.Context, *UpdateLaneRequest) (*UpdateLaneResponse, error)
	UpdateLaneOrder(context.Context, *UpdateLaneOrderRequest) (*UpdateLaneOrderResponse, error)
	DeleteLane(context.Context, *DeleteLaneRequest) (*DeleteLaneResponse, error)
	CreateOutlineItem(context.Context, *CreateOutlineItemRequest) (*CreateOutlineItemResponse, error)
	UpdateOutlineItem(context.Context, *UpdateOutlineItemRequest) (*UpdateOutlineItemResponse, error)
	DeleteOutlineItem(context.Context, *DeleteOutlineItemRequest) (*DeleteOutlineItemResponse, error)
	// GetResourceProject resolves which project owns a sub-resource (beat, lane,
	// connection, outline item, or element). The gateway calls it to authorize
	// mutations against the resource's real project. It is an internal lookup —
	// no ownership check — so the gateway must authorize the returned project.
	GetResourceProject(context.Context, *GetResourceProjectRequest) (*GetResourceProjectResponse, error)
	// SyncProject reconciles one project bidirectionally: it applies the caller's
	// pushed changes (upsert-by-id, server-stamped updated_at, last-sync-wins) and
	// returns every row changed since the caller's cursor. See SYNC_DESIGN.md.
	SyncProject(context.Context, *SyncProjectRequest) (*SyncProjectResponse, error)
	// SyncVault reconciles a vault project's files bidirectionally, keyed by path
	// (upsert-by-path, server-stamped updated_at, last-sync-wins). Paginated: when
	// the response sets has_more, call again with the returned cursor until it is
	// false. See SYNC_DESIGN.md ("vault file sync").
	SyncVault(context.Context, *SyncVaultRequest) (*SyncVaultResponse, error)
	mustEmbedUnimplementedScriptsServiceServer()
}

// UnimplementedScriptsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedScriptsServiceServer struct{}

func (UnimplementedScriptsServiceServer) CreateProject(context.Context, *CreateProjectRequest) (*CreateProjectResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateProject not implemented")
}
func (UnimplementedScriptsServiceServer) GetProject(context.Context, *GetProjectRequest) (*GetProjectResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetProject not implemented")
}
func (UnimplementedScriptsServiceServer) UpdateProject(context.Context, *UpdateProjectRequest) (*UpdateProjectResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateProject not implemented")
}
func (UnimplementedScriptsServiceServer) ToggleProjectStar(context.Context, *ToggleProjectStarRequest) (*ToggleProjectStarResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ToggleProjectStar not implemented")
}
func (UnimplementedScriptsServiceServer) DeleteProject(context.Context, *DeleteProjectRequest) (*DeleteProjectResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteProject not implemented")
}
func (UnimplementedScriptsServiceServer) GetUserProjects(context.Context, *GetUserProjectsRequest) (*GetUserProjectsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserProjects not implemented")
}
func (UnimplementedScriptsServiceServer) GetOrgProjects(context.Context, *GetOrgProjectsRequest) (*GetOrgProjectsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetOrgProjects not implemented")
}
func (UnimplementedScriptsServiceServer) CreateOutlineUnit(context.Context, *CreateOutlineUnitRequest) (*CreateOutlineUnitResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateOutlineUnit not implemented")
}
func (UnimplementedScriptsServiceServer) GetProjectOutline(context.Context, *GetProjectOutlineRequest) (*GetProjectOutlineResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetProjectOutline not implemented")
}
func (UnimplementedScriptsServiceServer) UpdateOutlineUnit(context.Context, *UpdateOutlineUnitRequest) (*UpdateOutlineUnitResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateOutlineUnit not implemented")
}
func (UnimplementedScriptsServiceServer) DeleteOutlineUnit(context.Context, *DeleteOutlineUnitRequest) (*DeleteOutlineUnitResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteOutlineUnit not implemented")
}
func (UnimplementedScriptsServiceServer) CreateScene(context.Context, *CreateSceneRequest) (*CreateSceneResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateScene not implemented")
}
func (UnimplementedScriptsServiceServer) GetProjectScenes(context.Context, *GetProjectScenesRequest) (*GetProjectScenesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetProjectScenes not implemented")
}
func (UnimplementedScriptsServiceServer) UpdateScene(context.Context, *UpdateSceneRequest) (*UpdateSceneResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateScene not implemented")
}
func (UnimplementedScriptsServiceServer) DeleteScene(context.Context, *DeleteSceneRequest) (*DeleteSceneResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteScene not implemented")
}
func (UnimplementedScriptsServiceServer) CreateCharacter(context.Context, *CreateCharacterRequest) (*CreateCharacterResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateCharacter not implemented")
}
func (UnimplementedScriptsServiceServer) GetProjectCharacters(context.Context, *GetProjectCharactersRequest) (*GetProjectCharactersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetProjectCharacters not implemented")
}
func (UnimplementedScriptsServiceServer) UpdateCharacter(context.Context, *UpdateCharacterRequest) (*UpdateCharacterResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateCharacter not implemented")
}
func (UnimplementedScriptsServiceServer) CreateLocation(context.Context, *CreateLocationRequest) (*CreateLocationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateLocation not implemented")
}
func (UnimplementedScriptsServiceServer) GetProjectLocations(context.Context, *GetProjectLocationsRequest) (*GetProjectLocationsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetProjectLocations not implemented")
}
func (UnimplementedScriptsServiceServer) CreateElement(context.Context, *CreateElementRequest) (*CreateElementResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateElement not implemented")
}
func (UnimplementedScriptsServiceServer) UpdateElement(context.Context, *UpdateElementRequest) (*UpdateElementResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateElement not implemented")
}
func (UnimplementedScriptsServiceServer) GetSceneElements(context.Context, *GetSceneElementsRequest) (*GetSceneElementsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSceneElements not implemented")
}
func (UnimplementedScriptsServiceServer) DeleteScriptElement(context.Context, *DeleteScriptElementRequest) (*DeleteScriptElementResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteScriptElement not implemented")
}
func (UnimplementedScriptsServiceServer) BatchCreateElements(context.Context, *BatchCreateElementsRequest) (*BatchCreateElementsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BatchCreateElements not implemented")
}
func (UnimplementedScriptsServiceServer) CreateBeat(context.Context, *CreateBeatRequest) (*CreateBeatResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateBeat not implemented")
}
func (UnimplementedScriptsServiceServer) GetBeat(context.Context, *GetBeatRequest) (*GetBeatResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBeat not implemented")
}
func (UnimplementedScriptsServiceServer) GetProjectBeatBoard(context.Context, *GetProjectBeatBoardRequest) (*GetProjectBeatBoardResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetProjectBeatBoard not implemented")
}
func (UnimplementedScriptsServiceServer) UpdateBeat(context.Context, *UpdateBeatRequest) (*UpdateBeatResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateBeat not implemented")
}
func (UnimplementedScriptsServiceServer) DeleteBeat(context.Context, *DeleteBeatRequest) (*DeleteBeatResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteBeat not implemented")
}
func (UnimplementedScriptsServiceServer) CreateConnection(context.Context, *CreateConnectionRequest) (*CreateConnectionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateConnection not implemented")
}
func (UnimplementedScriptsServiceServer) DeleteConnection(context.Context, *DeleteConnectionRequest) (*DeleteConnectionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteConnection not implemented")
}
func (UnimplementedScriptsServiceServer) CreateLane(context.Context, *CreateLaneRequest) (*CreateLaneResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateLane not implemented")
}
func (UnimplementedScriptsServiceServer) GetProjectLanes(context.Context, *GetProjectLanesRequest) (*GetProjectLanesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetProjectLanes not implemented")
}
func (UnimplementedScriptsServiceServer) UpdateLane(context.Context, *UpdateLaneRequest) (*UpdateLaneResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateLane not implemented")
}
func (UnimplementedScriptsServiceServer) UpdateLaneOrder(context.Context, *UpdateLaneOrderRequest) (*UpdateLaneOrderResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateLaneOrder not implemented")
}
func (UnimplementedScriptsServiceServer) DeleteLane(context.Context, *DeleteLaneRequest) (*DeleteLaneResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteLane not implemented")
}
func (UnimplementedScriptsServiceServer) CreateOutlineItem(context.Context, *CreateOutlineItemRequest) (*CreateOutlineItemResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateOutlineItem not implemented")
}
func (UnimplementedScriptsServiceServer) UpdateOutlineItem(context.Context, *UpdateOutlineItemRequest) (*UpdateOutlineItemResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateOutlineItem not implemented")
}
func (UnimplementedScriptsServiceServer) DeleteOutlineItem(context.Context, *DeleteOutlineItemRequest) (*DeleteOutlineItemResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteOutlineItem not implemented")
}
func (UnimplementedScriptsServiceServer) GetResourceProject(context.Context, *GetResourceProjectRequest) (*GetResourceProjectResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetResourceProject not implemented")
}
func (UnimplementedScriptsServiceServer) SyncProject(context.Context, *SyncProjectRequest) (*SyncProjectResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SyncProject not implemented")
}
func (UnimplementedScriptsServiceServer) SyncVault(context.Context, *SyncVaultRequest) (*SyncVaultResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SyncVault not implemented")
}
func (UnimplementedScriptsServiceServer) mustEmbedUnimplementedScriptsServiceServer() {}
func (UnimplementedScriptsServiceServer) testEmbeddedByValue()                        {}

// UnsafeScriptsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ScriptsServiceServer will
// result in compilation errors.
type UnsafeScriptsServiceServer interface {
	mustEmbedUnimplementedScriptsServiceServer()
}

func RegisterScriptsServiceServer(s grpc.ServiceRegistrar, srv ScriptsServiceServer) {
	// If the following call panics, it indicates UnimplementedScriptsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ScriptsService_ServiceDesc, srv)
}

func _ScriptsService_CreateProject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateProjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScriptsServiceServer).CreateProject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScriptsService_CreateProject_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScriptsServiceServer).CreateProject(ctx, req.(*CreateProjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ScriptsService_GetProject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScriptsServiceServer).GetProject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScriptsService_GetProject_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScriptsServiceServer).GetProject(ctx, req.(*GetProjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ScriptsService_UpdateProject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateProjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScriptsServiceServer).UpdateProject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScriptsService_UpdateProject_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScriptsServiceServer).UpdateProject(ctx, req.(*UpdateProjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ScriptsService_ToggleProjectStar_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ToggleProjectStarRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScriptsServiceServer).ToggleProjectStar(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScriptsService_ToggleProjectStar_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScriptsServiceServer).ToggleProjectStar(ctx, req.(*ToggleProjectStarRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ScriptsService_DeleteProject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteProjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScriptsServiceServer).DeleteProject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScriptsService_DeleteProject_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScriptsServiceServer).DeleteProject(ctx, req.(*DeleteProjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ScriptsService_GetUserProjects_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserProjectsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScriptsServiceServer).GetUserProjects(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScriptsService_GetUserProjects_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScriptsServiceServer).GetUserProjects(ctx, req.(*GetUserProjectsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ScriptsService_GetOrgProjects_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOrgProjectsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScriptsServiceServer).GetOrgProjects(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScriptsService_GetOrgProjects_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScriptsServiceServer).GetOrgProjects(ctx, req.(*GetOrgProjectsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ScriptsService_CreateOutlineUnit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateOutlineUnitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScriptsServiceServer).CreateOutlineUnit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScriptsService_CreateOutlineUnit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScriptsServiceServer).CreateOutlineUnit(ctx, req.(*CreateOutlineUnitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ScriptsService_GetProjectOutline_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProjectOutlineRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScriptsServiceServer).GetProjectOutline(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScriptsService_GetProjectOutline_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScriptsServiceServer).GetProjectOutline(ctx, req.(*GetProjectOutlineRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ScriptsService_UpdateOutlineUnit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateOutlineUnitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScriptsServiceServer).UpdateOutlineUnit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScriptsService_UpdateOutlineUnit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScriptsServiceServer).UpdateOutlineUnit(ctx, req.(*UpdateOutlineUnitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ScriptsService_DeleteOutlineUnit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteOutlineUnitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScriptsServiceServer).DeleteOutlineUnit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScriptsService_DeleteOutlineUnit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScriptsServiceServer).DeleteOutlineUnit(ctx, req.(*DeleteOutlineUnitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ScriptsService_CreateScene_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSceneRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScriptsServiceServer).CreateScene(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScriptsService_CreateScene_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScriptsServiceServer).CreateScene(ctx, req.(*CreateSceneRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ScriptsService_GetProjectScenes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProjectScenesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScriptsServiceServer).GetProjectScenes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScriptsService_GetProjectScenes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScriptsServiceServer).GetProjectScenes(ctx, req.(*GetProjectScenesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ScriptsService_UpdateScene_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateSceneRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScriptsServiceServer).UpdateScene(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScriptsService_UpdateScene_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScriptsServiceServer).UpdateScene(ctx, req.(*UpdateSceneRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ScriptsService_DeleteScene_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteSceneRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScriptsServiceServer).DeleteScene(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScriptsService_DeleteScene_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScriptsServiceServer).DeleteScene(ctx, req.(*DeleteSceneRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ScriptsService_CreateCharacter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCharacterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScriptsServiceServer).CreateCharacter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScriptsService_CreateCharacter_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScriptsServiceServer).CreateCharacter(ctx, req.(*CreateCharacterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ScriptsService_GetProjectCharacters_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProjectCharactersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScriptsServiceServer).GetProjectCharacters(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScriptsService_GetProjectCharacters_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScriptsServiceServer).GetProjectCharacters(ctx, req.(*GetProjectCharactersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ScriptsService_UpdateCharacter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateCharacterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScriptsServiceServer).UpdateCharacter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScriptsService_UpdateCharacter_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScriptsServiceServer).UpdateCharacter(ctx, req.(*UpdateCharacterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ScriptsService_CreateLocation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateLocationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScriptsServiceServer).CreateLocation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScriptsService_CreateLocation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScriptsServiceServer).CreateLocation(ctx, req.(*CreateLocationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ScriptsService_GetProjectLocations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProjectLocationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScriptsServiceServer).GetProjectLocations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScriptsService_GetProjectLocations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScriptsServiceServer).GetProjectLocations(ctx, req.(*GetProjectLocationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ScriptsService_CreateElement_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateElementRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScriptsServiceServer).CreateElement(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScriptsService_CreateElement_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScriptsServiceServer).CreateElement(ctx, req.(*CreateElementRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ScriptsService_UpdateElement_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateElementRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScriptsServiceServer).UpdateElement(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScriptsService_UpdateElement_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScriptsServiceServer).UpdateElement(ctx, req.(*UpdateElementRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ScriptsService_GetSceneElements_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSceneElementsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScriptsServiceServer).GetSceneElements(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScriptsService_GetSceneElements_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScriptsServiceServer).GetSceneElements(ctx, req.(*GetSceneElementsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ScriptsService_DeleteScriptElement_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteScriptElementRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScriptsServiceServer).DeleteScriptElement(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScriptsService_DeleteScriptElement_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScriptsServiceServer).DeleteScriptElement(ctx, req.(*DeleteScriptElementRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ScriptsService_BatchCreateElements_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchCreateElementsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScriptsServiceServer).BatchCreateElements(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScriptsService_BatchCreateElements_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScriptsServiceServer).BatchCreateElements(ctx, req.(*BatchCreateElementsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ScriptsService_CreateBeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateBeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScriptsServiceServer).CreateBeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScriptsService_CreateBeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScriptsServiceServer).CreateBeat(ctx, req.(*CreateBeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ScriptsService_GetBeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScriptsServiceServer).GetBeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScriptsService_GetBeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScriptsServiceServer).GetBeat(ctx, req.(*GetBeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ScriptsService_GetProjectBeatBoard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProjectBeatBoardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScriptsServiceServer).GetProjectBeatBoard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScriptsService_GetProjectBeatBoard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScriptsServiceServer).GetProjectBeatBoard(ctx, req.(*GetProjectBeatBoardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ScriptsService_UpdateBeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateBeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScriptsServiceServer).UpdateBeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScriptsService_UpdateBeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScriptsServiceServer).UpdateBeat(ctx, req.(*UpdateBeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ScriptsService_DeleteBeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteBeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScriptsServiceServer).DeleteBeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScriptsService_DeleteBeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScriptsServiceServer).DeleteBeat(ctx, req.(*DeleteBeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ScriptsService_CreateConnection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateConnectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScriptsServiceServer).CreateConnection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScriptsService_CreateConnection_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScriptsServiceServer).CreateConnection(ctx, req.(*CreateConnectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ScriptsService_DeleteConnection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteConnectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScriptsServiceServer).DeleteConnection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScriptsService_DeleteConnection_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScriptsServiceServer).DeleteConnection(ctx, req.(*DeleteConnectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ScriptsService_CreateLane_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateLaneRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScriptsServiceServer).CreateLane(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScriptsService_CreateLane_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScriptsServiceServer).CreateLane(ctx, req.(*CreateLaneRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ScriptsService_GetProjectLanes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProjectLanesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScriptsServiceServer).GetProjectLanes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScriptsService_GetProjectLanes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScriptsServiceServer).GetProjectLanes(ctx, req.(*GetProjectLanesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ScriptsService_UpdateLane_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateLaneRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScriptsServiceServer).UpdateLane(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScriptsService_UpdateLane_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScriptsServiceServer).UpdateLane(ctx, req.(*UpdateLaneRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ScriptsService_UpdateLaneOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateLaneOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScriptsServiceServer).UpdateLaneOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScriptsService_UpdateLaneOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScriptsServiceServer).UpdateLaneOrder(ctx, req.(*UpdateLaneOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ScriptsService_DeleteLane_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteLaneRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScriptsServiceServer).DeleteLane(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScriptsService_DeleteLane_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScriptsServiceServer).DeleteLane(ctx, req.(*DeleteLaneRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ScriptsService_CreateOutlineItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateOutlineItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScriptsServiceServer).CreateOutlineItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScriptsService_CreateOutlineItem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScriptsServiceServer).CreateOutlineItem(ctx, req.(*CreateOutlineItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ScriptsService_UpdateOutlineItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateOutlineItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScriptsServiceServer).UpdateOutlineItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScriptsService_UpdateOutlineItem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScriptsServiceServer).UpdateOutlineItem(ctx, req.(*UpdateOutlineItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ScriptsService_DeleteOutlineItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteOutlineItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScriptsServiceServer).DeleteOutlineItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScriptsService_DeleteOutlineItem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScriptsServiceServer).DeleteOutlineItem(ctx, req.(*DeleteOutlineItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ScriptsService_GetResourceProject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetResourceProjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScriptsServiceServer).GetResourceProject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScriptsService_GetResourceProject_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScriptsServiceServer).GetResourceProject(ctx, req.(*GetResourceProjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ScriptsService_SyncProject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncProjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScriptsServiceServer).SyncProject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScriptsService_SyncProject_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScriptsServiceServer).SyncProject(ctx, req.(*SyncProjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ScriptsService_SyncVault_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncVaultRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScriptsServiceServer).SyncVault(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScriptsService_SyncVault_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScriptsServiceServer).SyncVault(ctx, req.(*SyncVaultRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ScriptsService_ServiceDesc is the grpc.ServiceDesc for ScriptsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ScriptsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "scripts.ScriptsService",
	HandlerType: (*ScriptsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateProject",
			Handler:    _ScriptsService_CreateProject_Handler,
		},
		{
			MethodName: "GetProject",
			Handler:    _ScriptsService_GetProject_Handler,
		},
		{
			MethodName: "UpdateProject",
			Handler:    _ScriptsService_UpdateProject_Handler,
		},
		{
			MethodName: "ToggleProjectStar",
			Handler:    _ScriptsService_ToggleProjectStar_Handler,
		},
		{
			MethodName: "DeleteProject",
			Handler:    _ScriptsService_DeleteProject_Handler,
		},
		{
			MethodName: "GetUserProjects",
			Handler:    _ScriptsService_GetUserProjects_Handler,
		},
		{
			MethodName: "GetOrgProjects",
			Handler:    _ScriptsService_GetOrgProjects_Handler,
		},
		{
			MethodName: "CreateOutlineUnit",
			Handler:    _ScriptsService_CreateOutlineUnit_Handler,
		},
		{
			MethodName: "GetProjectOutline",
			Handler:    _ScriptsService_GetProjectOutline_Handler,
		},
		{
			MethodName: "UpdateOutlineUnit",
			Handler:    _ScriptsService_UpdateOutlineUnit_Handler,
		},
		{
			MethodName: "DeleteOutlineUnit",
			Handler:    _ScriptsService_DeleteOutlineUnit_Handler,
		},
		{
			MethodName: "CreateScene",
			Handler:    _ScriptsService_CreateScene_Handler,
		},
		{
			MethodName: "GetProjectScenes",
			Handler:    _ScriptsService_GetProjectScenes_Handler,
		},
		{
			MethodName: "UpdateScene",
			Handler:    _ScriptsService_UpdateScene_Handler,
		},
		{
			MethodName: "DeleteScene",
			Handler:    _ScriptsService_DeleteScene_Handler,
		},
		{
			MethodName: "CreateCharacter",
			Handler:    _ScriptsService_CreateCharacter_Handler,
		},
		{
			MethodName: "GetProjectCharacters",
			Handler:    _ScriptsService_GetProjectCharacters_Handler,
		},
		{
			MethodName: "UpdateCharacter",
			Handler:    _ScriptsService_UpdateCharacter_Handler,
		},
		{
			MethodName: "CreateLocation",
			Handler:    _ScriptsService_CreateLocation_Handler,
		},
		{
			MethodName: "GetProjectLocations",
			Handler:    _ScriptsService_GetProjectLocations_Handler,
		},
		{
			MethodName: "CreateElement",
			Handler:    _ScriptsService_CreateElement_Handler,
		},
		{
			MethodName: "UpdateElement",
			Handler:    _ScriptsService_UpdateElement_Handler,
		},
		{
			MethodName: "GetSceneElements",
			Handler:    _ScriptsService_GetSceneElements_Handler,
		},
		{
			MethodName: "DeleteScriptElement",
			Handler:    _ScriptsService_DeleteScriptElement_Handler,
		},
		{
			MethodName: "BatchCreateElements",
			Handler:    _ScriptsService_BatchCreateElements_Handler,
		},
		{
			MethodName: "CreateBeat",
			Handler:    _ScriptsService_CreateBeat_Handler,
		},
		{
			MethodName: "GetBeat",
			Handler:    _ScriptsService_GetBeat_Handler,
		},
		{
			MethodName: "GetProjectBeatBoard",
			Handler:    _ScriptsService_GetProjectBeatBoard_Handler,
		},
		{
			MethodName: "UpdateBeat",
			Handler:    _ScriptsService_UpdateBeat_Handler,
		},
		{
			MethodName: "DeleteBeat",
			Handler:    _ScriptsService_DeleteBeat_Handler,
		},
		{
			MethodName: "CreateConnection",
			Handler:    _ScriptsService_CreateConnection_Handler,
		},
		{
			MethodName: "DeleteConnection",
			Handler:    _ScriptsService_DeleteConnection_Handler,
		},
		{
			MethodName: "CreateLane",
			Handler:    _ScriptsService_CreateLane_Handler,
		},
		{
			MethodName: "GetProjectLanes",
			Handler:    _ScriptsService_GetProjectLanes_Handler,
		},
		{
			MethodName: "UpdateLane",
			Handler:    _ScriptsService_UpdateLane_Handler,
		},
		{
			MethodName: "UpdateLaneOrder",
			Handler:    _ScriptsService_UpdateLaneOrder_Handler,
		},
		{
			MethodName: "DeleteLane",
			Handler:    _ScriptsService_DeleteLane_Handler,
		},
		{
			MethodName: "CreateOutlineItem",
			Handler:    _ScriptsService_CreateOutlineItem_Handler,
		},
		{
			MethodName: "UpdateOutlineItem",
			Handler:    _ScriptsService_UpdateOutlineItem_Handler,
		},
		{
			MethodName: "DeleteOutlineItem",
			Handler:    _ScriptsService_DeleteOutlineItem_Handler,
		},
		{
			MethodName: "GetResourceProject",
			Handler:    _ScriptsService_GetResourceProject_Handler,
		},
		{
			MethodName: "SyncProject",
			Handler:    _ScriptsService_SyncProject_Handler,
		},
		{
			MethodName: "SyncVault",
			Handler:    _ScriptsService_SyncVault_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "scripts/scripts.proto",
}
