import {
  Clapperboard,
  User,
  MessageSquare,
  Parentheses,
  ArrowRight,
  Video,
  MapPinned,
  Type,
  StickyNote,
  List,
  Play,
  Square,
  Music,
  Layers,
  Columns
} from "lucide-react"

// Define the order of elements as they should appear in the toolbar
export const ELEMENT_ORDER = [
  "SCENE_HEADING",
  "ACTION",
  "CHARACTER",
  "PARENTHETICAL",
  "DIALOG",
  "TRANSITION",
  "SHOT",
  "TEXT",
  "NOTE",
  "OUTLINE",
  "NEW_ACT",
  "END_ACT",
  "LYRICS",
  "SEQUENCE",
  "DUAL_DIALOG",
] as const

export const SCRIPT_ELEMENT_CONFIG = {
  SCENE_HEADING: {
    tooltip: "Scene",
    toolbarColor: "hover:bg-green-50 hover:text-green-700 dark:hover:bg-green-900/30 dark:hover:text-green-400",
    icon: MapPinned,
    editorClasses: "uppercase font-bold max-w-full",
  },
  ACTION: {
    tooltip: "Action",
    icon: Clapperboard,
    toolbarColor: "hover:bg-purple-50 hover:text-purple-700 dark:hover:bg-purple-900/30 dark:hover:text-purple-400",
    badgeColor: "bg-purple-100 text-purple-700 border-purple-200 dark:bg-purple-900/30 dark:text-purple-400 dark:border-purple-800",
    editorClasses: "w-full block",
  },
  CHARACTER: {
    tooltip: "Character",
    icon: User,
    toolbarColor: "hover:bg-blue-50 hover:text-blue-700 dark:hover:bg-blue-900/30 dark:hover:text-blue-400",
    badgeColor: "bg-blue-100 text-blue-700 border-blue-200 dark:bg-blue-900/30 dark:text-blue-400 dark:border-blue-800",
    editorClasses: "text-center uppercase max-w-full mx-auto",
  },
  PARENTHETICAL: {
    tooltip: "Parens",
    icon: Parentheses,
    toolbarColor: "hover:bg-gray-50 hover:text-gray-700 dark:hover:bg-gray-700/50 dark:hover:text-gray-300",
    badgeColor: "bg-gray-100 text-gray-700 border-gray-200 dark:bg-gray-800 dark:text-gray-400 dark:border-gray-700",
    editorClasses: "ml-[1.6in] mr-[1.6in] text-sm text-gray-500 max-w-[calc(100%-3.2in)]",
  },
  DIALOG: {
    tooltip: "Dialogue",
    icon: MessageSquare,
    toolbarColor: "hover:bg-green-50 hover:text-green-700 dark:hover:bg-green-900/30 dark:hover:text-green-400",
    badgeColor: "bg-green-100 text-green-700 border-green-200 dark:bg-green-900/30 dark:text-green-400 dark:border-green-800",
    editorClasses: "ml-[1.0in] mr-[1.0in] max-w-[calc(100%-2in)]",
  },
  TRANSITION: {
    tooltip: "Transition",
    icon: ArrowRight,
    toolbarColor: "hover:bg-red-50 hover:text-red-700 dark:hover:bg-red-900/30 dark:hover:text-red-400",
    badgeColor: "bg-red-100 text-red-700 border-red-200 dark:bg-red-900/30 dark:text-red-400 dark:border-red-800",
    editorClasses: "uppercase text-right max-w-full",
  },
  SHOT: {
    tooltip: "Shot",
    icon: Video,
    toolbarColor: "hover:bg-orange-50 hover:text-orange-700 dark:hover:bg-orange-900/30 dark:hover:text-orange-400",
    badgeColor: "bg-orange-100 text-orange-700 border-orange-200 dark:bg-orange-900/30 dark:text-orange-400 dark:border-orange-800",
    editorClasses: "uppercase max-w-full",
  },
  TEXT: {
    tooltip: "Text",
    icon: Type,
    toolbarColor: "hover:bg-slate-50 hover:text-slate-700 dark:hover:bg-slate-900/30 dark:hover:text-slate-400",
    badgeColor: "bg-slate-100 text-slate-700 border-slate-200 dark:bg-slate-900/30 dark:text-slate-400 dark:border-slate-800",
    editorClasses: "w-full block",
    comingSoon: true,
  },
  NOTE: {
    tooltip: "Note",
    icon: StickyNote,
    toolbarColor: "hover:bg-yellow-50 hover:text-yellow-700 dark:hover:bg-yellow-900/30 dark:hover:text-yellow-400",
    badgeColor: "bg-yellow-100 text-yellow-700 border-yellow-200 dark:bg-yellow-900/30 dark:text-yellow-400 dark:border-yellow-800",
    editorClasses: "w-full block italic text-yellow-700 dark:text-yellow-400 bg-yellow-50/50 dark:bg-yellow-900/10 px-2 py-1 rounded border-l-2 border-yellow-400",
    comingSoon: true,
  },
  OUTLINE: {
    tooltip: "Outline",
    icon: List,
    toolbarColor: "hover:bg-indigo-50 hover:text-indigo-700 dark:hover:bg-indigo-900/30 dark:hover:text-indigo-400",
    badgeColor: "bg-indigo-100 text-indigo-700 border-indigo-200 dark:bg-indigo-900/30 dark:text-indigo-400 dark:border-indigo-800",
    editorClasses: "w-full block text-indigo-700 dark:text-indigo-400 bg-indigo-50/50 dark:bg-indigo-900/10 px-2 py-1 rounded border-l-2 border-indigo-400",
    comingSoon: true,
  },
  NEW_ACT: {
    tooltip: "New Act",
    icon: Play,
    toolbarColor: "hover:bg-emerald-50 hover:text-emerald-700 dark:hover:bg-emerald-900/30 dark:hover:text-emerald-400",
    badgeColor: "bg-emerald-100 text-emerald-700 border-emerald-200 dark:bg-emerald-900/30 dark:text-emerald-400 dark:border-emerald-800",
    editorClasses: "w-full block text-center uppercase font-bold text-lg tracking-wide py-2",
    comingSoon: true,
  },
  END_ACT: {
    tooltip: "End Act",
    icon: Square,
    toolbarColor: "hover:bg-rose-50 hover:text-rose-700 dark:hover:bg-rose-900/30 dark:hover:text-rose-400",
    badgeColor: "bg-rose-100 text-rose-700 border-rose-200 dark:bg-rose-900/30 dark:text-rose-400 dark:border-rose-800",
    editorClasses: "w-full block text-center uppercase font-bold tracking-wide py-2",
    comingSoon: true,
  },
  LYRICS: {
    tooltip: "Lyrics",
    icon: Music,
    toolbarColor: "hover:bg-pink-50 hover:text-pink-700 dark:hover:bg-pink-900/30 dark:hover:text-pink-400",
    badgeColor: "bg-pink-100 text-pink-700 border-pink-200 dark:bg-pink-900/30 dark:text-pink-400 dark:border-pink-800",
    editorClasses: "ml-[1.0in] mr-[1.0in] max-w-[calc(100%-2in)] italic",
    comingSoon: true,
  },
  SEQUENCE: {
    tooltip: "Sequence",
    icon: Layers,
    toolbarColor: "hover:bg-cyan-50 hover:text-cyan-700 dark:hover:bg-cyan-900/30 dark:hover:text-cyan-400",
    badgeColor: "bg-cyan-100 text-cyan-700 border-cyan-200 dark:bg-cyan-900/30 dark:text-cyan-400 dark:border-cyan-800",
    editorClasses: "w-full block uppercase font-semibold text-cyan-700 dark:text-cyan-400",
    comingSoon: true,
  },
  DUAL_DIALOG: {
    tooltip: "Dual",
    icon: Columns,
    toolbarColor: "hover:bg-violet-50 hover:text-violet-700 dark:hover:bg-violet-900/30 dark:hover:text-violet-400",
    badgeColor: "bg-violet-100 text-violet-700 border-violet-200 dark:bg-violet-900/30 dark:text-violet-400 dark:border-violet-800",
    editorClasses: "ml-[0.5in] mr-[0.5in] max-w-[calc(100%-1in)]",
    comingSoon: true,
  },
} as const

export type ToolbarScriptElementType = keyof Omit<typeof SCRIPT_ELEMENT_CONFIG, "SCENE_HEADING">
