// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: notifications/notifications.proto

package notifications

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// NotificationPreferences mirrors the seven toggles surfaced in the client
// settings UI. Each field gates one delivery decision the notification worker
// makes when it consumes a domain event. Defaults (when a user has never saved
// preferences) are all-on except marketing_emails.
type NotificationPreferences struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	UserId                 string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	EmailComments          bool                   `protobuf:"varint,2,opt,name=email_comments,json=emailComments,proto3" json:"email_comments,omitempty"`                              // "someone commented on your project"
	EmailMentions          bool                   `protobuf:"varint,3,opt,name=email_mentions,json=emailMentions,proto3" json:"email_mentions,omitempty"`                              // "someone mentioned you" (no event source yet)
	EmailProjectUpdates    bool                   `protobuf:"varint,4,opt,name=email_project_updates,json=emailProjectUpdates,proto3" json:"email_project_updates,omitempty"`          // "a project you collaborate on changed" (no event source yet)
	EmailCollaboratorJoins bool                   `protobuf:"varint,5,opt,name=email_collaborator_joins,json=emailCollaboratorJoins,proto3" json:"email_collaborator_joins,omitempty"` // "someone joined your project"
	InAppNotifications     bool                   `protobuf:"varint,6,opt,name=in_app_notifications,json=inAppNotifications,proto3" json:"in_app_notifications,omitempty"`             // master switch for the in-app feed
	MarketingEmails        bool                   `protobuf:"varint,7,opt,name=marketing_emails,json=marketingEmails,proto3" json:"marketing_emails,omitempty"`                        // promotional broadcasts (no broadcast system yet)
	ProductUpdates         bool                   `protobuf:"varint,8,opt,name=product_updates,json=productUpdates,proto3" json:"product_updates,omitempty"`                           // product/feature announcements
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *NotificationPreferences) Reset() {
	*x = NotificationPreferences{}
	mi := &file_notifications_notifications_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotificationPreferences) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotificationPreferences) ProtoMessage() {}

func (x *NotificationPreferences) ProtoReflect() protoreflect.Message {
	mi := &file_notifications_notifications_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotificationPreferences.ProtoReflect.Descriptor instead.
func (*NotificationPreferences) Descriptor() ([]byte, []int) {
	return file_notifications_notifications_proto_rawDescGZIP(), []int{0}
}

func (x *NotificationPreferences) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *NotificationPreferences) GetEmailComments() bool {
	if x != nil {
		return x.EmailComments
	}
	return false
}

func (x *NotificationPreferences) GetEmailMentions() bool {
	if x != nil {
		return x.EmailMentions
	}
	return false
}

func (x *NotificationPreferences) GetEmailProjectUpdates() bool {
	if x != nil {
		return x.EmailProjectUpdates
	}
	return false
}

func (x *NotificationPreferences) GetEmailCollaboratorJoins() bool {
	if x != nil {
		return x.EmailCollaboratorJoins
	}
	return false
}

func (x *NotificationPreferences) GetInAppNotifications() bool {
	if x != nil {
		return x.InAppNotifications
	}
	return false
}

func (x *NotificationPreferences) GetMarketingEmails() bool {
	if x != nil {
		return x.MarketingEmails
	}
	return false
}

func (x *NotificationPreferences) GetProductUpdates() bool {
	if x != nil {
		return x.ProductUpdates
	}
	return false
}

type GetPreferencesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPreferencesRequest) Reset() {
	*x = GetPreferencesRequest{}
	mi := &file_notifications_notifications_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPreferencesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPreferencesRequest) ProtoMessage() {}

func (x *GetPreferencesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notifications_notifications_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPreferencesRequest.ProtoReflect.Descriptor instead.
func (*GetPreferencesRequest) Descriptor() ([]byte, []int) {
	return file_notifications_notifications_proto_rawDescGZIP(), []int{1}
}

func (x *GetPreferencesRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetPreferencesResponse struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Preferences   *NotificationPreferences `protobuf:"bytes,1,opt,name=preferences,proto3" json:"preferences,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPreferencesResponse) Reset() {
	*x = GetPreferencesResponse{}
	mi := &file_notifications_notifications_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPreferencesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPreferencesResponse) ProtoMessage() {}

func (x *GetPreferencesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notifications_notifications_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPreferencesResponse.ProtoReflect.Descriptor instead.
func (*GetPreferencesResponse) Descriptor() ([]byte, []int) {
	return file_notifications_notifications_proto_rawDescGZIP(), []int{2}
}

func (x *GetPreferencesResponse) GetPreferences() *NotificationPreferences {
	if x != nil {
		return x.Preferences
	}
	return nil
}

// UpdatePreferencesRequest carries the full preference set. The client always
// holds all seven toggles in state and sends them together, so there is no
// partial-update / field-mask ambiguity.
type UpdatePreferencesRequest struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Preferences   *NotificationPreferences `protobuf:"bytes,1,opt,name=preferences,proto3" json:"preferences,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePreferencesRequest) Reset() {
	*x = UpdatePreferencesRequest{}
	mi := &file_notifications_notifications_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePreferencesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePreferencesRequest) ProtoMessage() {}

func (x *UpdatePreferencesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notifications_notifications_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePreferencesRequest.ProtoReflect.Descriptor instead.
func (*UpdatePreferencesRequest) Descriptor() ([]byte, []int) {
	return file_notifications_notifications_proto_rawDescGZIP(), []int{3}
}

func (x *UpdatePreferencesRequest) GetPreferences() *NotificationPreferences {
	if x != nil {
		return x.Preferences
	}
	return nil
}

type UpdatePreferencesResponse struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Preferences   *NotificationPreferences `protobuf:"bytes,1,opt,name=preferences,proto3" json:"preferences,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePreferencesResponse) Reset() {
	*x = UpdatePreferencesResponse{}
	mi := &file_notifications_notifications_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePreferencesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePreferencesResponse) ProtoMessage() {}

func (x *UpdatePreferencesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notifications_notifications_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePreferencesResponse.ProtoReflect.Descriptor instead.
func (*UpdatePreferencesResponse) Descriptor() ([]byte, []int) {
	return file_notifications_notifications_proto_rawDescGZIP(), []int{4}
}

func (x *UpdatePreferencesResponse) GetPreferences() *NotificationPreferences {
	if x != nil {
		return x.Preferences
	}
	return nil
}

var File_notifications_notifications_proto protoreflect.FileDescriptor

const file_notifications_notifications_proto_rawDesc = "" +
	"\n" +
	"!notifications/notifications.proto\x12\rnotifications\"\xf4\x02\n" +
	"\x17NotificationPreferences\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12%\n" +
	"\x0eemail_comments\x18\x02 \x01(\bR\remailComments\x12%\n" +
	"\x0eemail_mentions\x18\x03 \x01(\bR\remailMentions\x122\n" +
	"\x15email_project_updates\x18\x04 \x01(\bR\x13emailProjectUpdates\x128\n" +
	"\x18email_collaborator_joins\x18\x05 \x01(\bR\x16emailCollaboratorJoins\x120\n" +
	"\x14in_app_notifications\x18\x06 \x01(\bR\x12inAppNotifications\x12)\n" +
	"\x10marketing_emails\x18\a \x01(\bR\x0fmarketingEmails\x12'\n" +
	"\x0fproduct_updates\x18\b \x01(\bR\x0eproductUpdates\"0\n" +
	"\x15GetPreferencesRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"b\n" +
	"\x16GetPreferencesResponse\x12H\n" +
	"\vpreferences\x18\x01 \x01(\v2&.notifications.NotificationPreferencesR\vpreferences\"d\n" +
	"\x18UpdatePreferencesRequest\x12H\n" +
	"\vpreferences\x18\x01 \x01(\v2&.notifications.NotificationPreferencesR\vpreferences\"e\n" +
	"\x19UpdatePreferencesResponse\x12H\n" +
	"\vpreferences\x18\x01 \x01(\v2&.notifications.NotificationPreferencesR\vpreferences2\xdd\x01\n" +
	"\x14NotificationsService\x12]\n" +
	"\x0eGetPreferences\x12$.notifications.GetPreferencesRequest\x1a%.notifications.GetPreferencesResponse\x12f\n" +
	"\x11UpdatePreferences\x12'.notifications.UpdatePreferencesRequest\x1a(.notifications.UpdatePreferencesResponseB'Z%inkwell/server/pkg/grpc/notificationsb\x06proto3"

var (
	file_notifications_notifications_proto_rawDescOnce sync.Once
	file_notifications_notifications_proto_rawDescData []byte
)

func file_notifications_notifications_proto_rawDescGZIP() []byte {
	file_notifications_notifications_proto_rawDescOnce.Do(func() {
		file_notifications_notifications_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_notifications_notifications_proto_rawDesc), len(file_notifications_notifications_proto_rawDesc)))
	})
	return file_notifications_notifications_proto_rawDescData
}

var file_notifications_notifications_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_notifications_notifications_proto_goTypes = []any{
	(*NotificationPreferences)(nil),   // 0: notifications.NotificationPreferences
	(*GetPreferencesRequest)(nil),     // 1: notifications.GetPreferencesRequest
	(*GetPreferencesResponse)(nil),    // 2: notifications.GetPreferencesResponse
	(*UpdatePreferencesRequest)(nil),  // 3: notifications.UpdatePreferencesRequest
	(*UpdatePreferencesResponse)(nil), // 4: notifications.UpdatePreferencesResponse
}
var file_notifications_notifications_proto_depIdxs = []int32{
	0, // 0: notifications.GetPreferencesResponse.preferences:type_name -> notifications.NotificationPreferences
	0, // 1: notifications.UpdatePreferencesRequest.preferences:type_name -> notifications.NotificationPreferences
	0, // 2: notifications.UpdatePreferencesResponse.preferences:type_name -> notifications.NotificationPreferences
	1, // 3: notifications.NotificationsService.GetPreferences:input_type -> notifications.GetPreferencesRequest
	3, // 4: notifications.NotificationsService.UpdatePreferences:input_type -> notifications.UpdatePreferencesRequest
	2, // 5: notifications.NotificationsService.GetPreferences:output_type -> notifications.GetPreferencesResponse
	4, // 6: notifications.NotificationsService.UpdatePreferences:output_type -> notifications.UpdatePreferencesResponse
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_notifications_notifications_proto_init() }
func file_notifications_notifications_proto_init() {
	if File_notifications_notifications_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_notifications_notifications_proto_rawDesc), len(file_notifications_notifications_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_notifications_notifications_proto_goTypes,
		DependencyIndexes: file_notifications_notifications_proto_depIdxs,
		MessageInfos:      file_notifications_notifications_proto_msgTypes,
	}.Build()
	File_notifications_notifications_proto = out.File
	file_notifications_notifications_proto_goTypes = nil
	file_notifications_notifications_proto_depIdxs = nil
}
