// Code generated by scripts/generate-tool-contracts.mjs; DO NOT EDIT.
import type { ToolSpec } from "@/lib/ai/providers"

export const SHARED_TOOL_CONTRACT_VERSION = 1
export const SHARED_TOOL_CONTRACTS: Record<string, ToolSpec> = {
  "list_projects": {
    "name": "list_projects",
    "description": "List the writer's projects: title, format, status and id for each. Use it to answer questions about their body of work, or to find the id of a project you need to act on.",
    "parameters": {
      "type": "object",
      "properties": {},
      "required": []
    }
  },
  "list_scenes": {
    "name": "list_scenes",
    "description": "List the scenes of the project this conversation is open on, in reading order, with the id needed to read one. Call this first when you need a scene id, or to get your bearings in the manuscript.",
    "parameters": {
      "type": "object",
      "properties": {},
      "required": []
    }
  },
  "read_scene": {
    "name": "read_scene",
    "description": "Read one scene of the project this conversation is open on, in full. Each line is prefixed with its element type — [paragraph], [dialogue], [action], [character] and so on — so you can see the shape of the writing and not only its words. Scene ids come from list_scenes.",
    "parameters": {
      "type": "object",
      "properties": {
        "scene_id": {
          "type": "string",
          "description": "The scene's id, as returned by list_scenes."
        }
      },
      "required": [
        "scene_id"
      ]
    }
  },
  "create_project": {
    "name": "create_project",
    "description": "Create a writing project owned by the caller, optionally in an organization where they have a writing role.",
    "parameters": {
      "type": "object",
      "properties": {
        "title": {
          "type": "string"
        },
        "description": {
          "type": "string"
        },
        "category": {
          "type": "string"
        },
        "org_id": {
          "type": "string"
        }
      },
      "required": [
        "title"
      ]
    }
  },
  "create_scene": {
    "name": "create_scene",
    "description": "Create a scene in the project this conversation is open on.",
    "parameters": {
      "type": "object",
      "properties": {
        "scene_heading": {
          "type": "string"
        },
        "content": {
          "type": "string"
        },
        "order_index": {
          "type": "integer"
        },
        "outline_unit_id": {
          "type": "string"
        }
      },
      "required": [
        "scene_heading"
      ]
    }
  },
  "append_to_scene": {
    "name": "append_to_scene",
    "description": "Append text to an existing scene without replacing its current content.",
    "parameters": {
      "type": "object",
      "properties": {
        "scene_id": {
          "type": "string"
        },
        "content": {
          "type": "string"
        }
      },
      "required": [
        "scene_id",
        "content"
      ]
    }
  },
  "add_beat": {
    "name": "add_beat",
    "description": "Add a story beat to the project this conversation is open on.",
    "parameters": {
      "type": "object",
      "properties": {
        "title": {
          "type": "string"
        },
        "description": {
          "type": "string"
        },
        "color": {
          "type": "string"
        },
        "act_number": {
          "type": "integer"
        },
        "order": {
          "type": "integer"
        }
      },
      "required": [
        "title"
      ]
    }
  },
  "rename_scene": {
    "name": "rename_scene",
    "description": "Rename a scene in the project this conversation is open on.",
    "parameters": {
      "type": "object",
      "properties": {
        "scene_id": {
          "type": "string"
        },
        "scene_heading": {
          "type": "string"
        }
      },
      "required": [
        "scene_id",
        "scene_heading"
      ]
    }
  }
}

export function sharedToolSpec(name: string): ToolSpec {
  const spec = SHARED_TOOL_CONTRACTS[name]
  if (!spec) throw new Error(`Unknown shared tool contract: ${name}`)
  return spec
}
